/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetActivitiesResponseAllOfDataInnerParticipantsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetActivitiesResponseAllOfDataInnerParticipantsInner{}

// GetActivitiesResponseAllOfDataInnerParticipantsInner struct for GetActivitiesResponseAllOfDataInnerParticipantsInner
type GetActivitiesResponseAllOfDataInnerParticipantsInner struct {
	// The ID of the person
	PersonId *int32 `json:"person_id,omitempty"`
	// Whether the person is the primary participant or not
	Primary              *bool `json:"primary,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetActivitiesResponseAllOfDataInnerParticipantsInner GetActivitiesResponseAllOfDataInnerParticipantsInner

// NewGetActivitiesResponseAllOfDataInnerParticipantsInner instantiates a new GetActivitiesResponseAllOfDataInnerParticipantsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetActivitiesResponseAllOfDataInnerParticipantsInner() *GetActivitiesResponseAllOfDataInnerParticipantsInner {
	this := GetActivitiesResponseAllOfDataInnerParticipantsInner{}
	return &this
}

// NewGetActivitiesResponseAllOfDataInnerParticipantsInnerWithDefaults instantiates a new GetActivitiesResponseAllOfDataInnerParticipantsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetActivitiesResponseAllOfDataInnerParticipantsInnerWithDefaults() *GetActivitiesResponseAllOfDataInnerParticipantsInner {
	this := GetActivitiesResponseAllOfDataInnerParticipantsInner{}
	return &this
}

// GetPersonId returns the PersonId field value if set, zero value otherwise.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) GetPersonId() int32 {
	if o == nil || IsNil(o.PersonId) {
		var ret int32
		return ret
	}
	return *o.PersonId
}

// GetPersonIdOk returns a tuple with the PersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) GetPersonIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PersonId) {
		return nil, false
	}
	return o.PersonId, true
}

// HasPersonId returns a boolean if a field has been set.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) HasPersonId() bool {
	if o != nil && !IsNil(o.PersonId) {
		return true
	}

	return false
}

// SetPersonId gets a reference to the given int32 and assigns it to the PersonId field.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) SetPersonId(v int32) {
	o.PersonId = &v
}

// GetPrimary returns the Primary field value if set, zero value otherwise.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) GetPrimary() bool {
	if o == nil || IsNil(o.Primary) {
		var ret bool
		return ret
	}
	return *o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) GetPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.Primary) {
		return nil, false
	}
	return o.Primary, true
}

// HasPrimary returns a boolean if a field has been set.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) HasPrimary() bool {
	if o != nil && !IsNil(o.Primary) {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given bool and assigns it to the Primary field.
func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) SetPrimary(v bool) {
	o.Primary = &v
}

func (o GetActivitiesResponseAllOfDataInnerParticipantsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActivitiesResponseAllOfDataInnerParticipantsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PersonId) {
		toSerialize["person_id"] = o.PersonId
	}
	if !IsNil(o.Primary) {
		toSerialize["primary"] = o.Primary
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetActivitiesResponseAllOfDataInnerParticipantsInner) UnmarshalJSON(data []byte) (err error) {
	varGetActivitiesResponseAllOfDataInnerParticipantsInner := _GetActivitiesResponseAllOfDataInnerParticipantsInner{}

	err = json.Unmarshal(data, &varGetActivitiesResponseAllOfDataInnerParticipantsInner)

	if err != nil {
		return err
	}

	*o = GetActivitiesResponseAllOfDataInnerParticipantsInner(varGetActivitiesResponseAllOfDataInnerParticipantsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "person_id")
		delete(additionalProperties, "primary")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetActivitiesResponseAllOfDataInnerParticipantsInner struct {
	value *GetActivitiesResponseAllOfDataInnerParticipantsInner
	isSet bool
}

func (v NullableGetActivitiesResponseAllOfDataInnerParticipantsInner) Get() *GetActivitiesResponseAllOfDataInnerParticipantsInner {
	return v.value
}

func (v *NullableGetActivitiesResponseAllOfDataInnerParticipantsInner) Set(val *GetActivitiesResponseAllOfDataInnerParticipantsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActivitiesResponseAllOfDataInnerParticipantsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActivitiesResponseAllOfDataInnerParticipantsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActivitiesResponseAllOfDataInnerParticipantsInner(val *GetActivitiesResponseAllOfDataInnerParticipantsInner) *NullableGetActivitiesResponseAllOfDataInnerParticipantsInner {
	return &NullableGetActivitiesResponseAllOfDataInnerParticipantsInner{value: val, isSet: true}
}

func (v NullableGetActivitiesResponseAllOfDataInnerParticipantsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActivitiesResponseAllOfDataInnerParticipantsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
