/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the AddProductFieldRequestUiVisibility type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddProductFieldRequestUiVisibility{}

// AddProductFieldRequestUiVisibility UI visibility settings for the field. Controls where the field appears in the Pipedrive web UI. Note that products have a simpler visibility model than other entity types.
type AddProductFieldRequestUiVisibility struct {
	// Whether the field is shown in the add product modal. Default is false. Cannot be set to false for the 'name' system field.
	AddVisibleFlag *bool `json:"add_visible_flag,omitempty"`
	// Whether the field is shown in the product details view. Default is true.
	DetailsVisibleFlag *bool `json:"details_visible_flag,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddProductFieldRequestUiVisibility AddProductFieldRequestUiVisibility

// NewAddProductFieldRequestUiVisibility instantiates a new AddProductFieldRequestUiVisibility object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddProductFieldRequestUiVisibility() *AddProductFieldRequestUiVisibility {
	this := AddProductFieldRequestUiVisibility{}
	var addVisibleFlag bool = false
	this.AddVisibleFlag = &addVisibleFlag
	var detailsVisibleFlag bool = true
	this.DetailsVisibleFlag = &detailsVisibleFlag
	return &this
}

// NewAddProductFieldRequestUiVisibilityWithDefaults instantiates a new AddProductFieldRequestUiVisibility object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddProductFieldRequestUiVisibilityWithDefaults() *AddProductFieldRequestUiVisibility {
	this := AddProductFieldRequestUiVisibility{}
	var addVisibleFlag bool = false
	this.AddVisibleFlag = &addVisibleFlag
	var detailsVisibleFlag bool = true
	this.DetailsVisibleFlag = &detailsVisibleFlag
	return &this
}

// GetAddVisibleFlag returns the AddVisibleFlag field value if set, zero value otherwise.
func (o *AddProductFieldRequestUiVisibility) GetAddVisibleFlag() bool {
	if o == nil || IsNil(o.AddVisibleFlag) {
		var ret bool
		return ret
	}
	return *o.AddVisibleFlag
}

// GetAddVisibleFlagOk returns a tuple with the AddVisibleFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddProductFieldRequestUiVisibility) GetAddVisibleFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.AddVisibleFlag) {
		return nil, false
	}
	return o.AddVisibleFlag, true
}

// HasAddVisibleFlag returns a boolean if a field has been set.
func (o *AddProductFieldRequestUiVisibility) HasAddVisibleFlag() bool {
	if o != nil && !IsNil(o.AddVisibleFlag) {
		return true
	}

	return false
}

// SetAddVisibleFlag gets a reference to the given bool and assigns it to the AddVisibleFlag field.
func (o *AddProductFieldRequestUiVisibility) SetAddVisibleFlag(v bool) {
	o.AddVisibleFlag = &v
}

// GetDetailsVisibleFlag returns the DetailsVisibleFlag field value if set, zero value otherwise.
func (o *AddProductFieldRequestUiVisibility) GetDetailsVisibleFlag() bool {
	if o == nil || IsNil(o.DetailsVisibleFlag) {
		var ret bool
		return ret
	}
	return *o.DetailsVisibleFlag
}

// GetDetailsVisibleFlagOk returns a tuple with the DetailsVisibleFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddProductFieldRequestUiVisibility) GetDetailsVisibleFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.DetailsVisibleFlag) {
		return nil, false
	}
	return o.DetailsVisibleFlag, true
}

// HasDetailsVisibleFlag returns a boolean if a field has been set.
func (o *AddProductFieldRequestUiVisibility) HasDetailsVisibleFlag() bool {
	if o != nil && !IsNil(o.DetailsVisibleFlag) {
		return true
	}

	return false
}

// SetDetailsVisibleFlag gets a reference to the given bool and assigns it to the DetailsVisibleFlag field.
func (o *AddProductFieldRequestUiVisibility) SetDetailsVisibleFlag(v bool) {
	o.DetailsVisibleFlag = &v
}

func (o AddProductFieldRequestUiVisibility) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddProductFieldRequestUiVisibility) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddVisibleFlag) {
		toSerialize["add_visible_flag"] = o.AddVisibleFlag
	}
	if !IsNil(o.DetailsVisibleFlag) {
		toSerialize["details_visible_flag"] = o.DetailsVisibleFlag
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddProductFieldRequestUiVisibility) UnmarshalJSON(data []byte) (err error) {
	varAddProductFieldRequestUiVisibility := _AddProductFieldRequestUiVisibility{}

	err = json.Unmarshal(data, &varAddProductFieldRequestUiVisibility)

	if err != nil {
		return err
	}

	*o = AddProductFieldRequestUiVisibility(varAddProductFieldRequestUiVisibility)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "add_visible_flag")
		delete(additionalProperties, "details_visible_flag")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddProductFieldRequestUiVisibility struct {
	value *AddProductFieldRequestUiVisibility
	isSet bool
}

func (v NullableAddProductFieldRequestUiVisibility) Get() *AddProductFieldRequestUiVisibility {
	return v.value
}

func (v *NullableAddProductFieldRequestUiVisibility) Set(val *AddProductFieldRequestUiVisibility) {
	v.value = val
	v.isSet = true
}

func (v NullableAddProductFieldRequestUiVisibility) IsSet() bool {
	return v.isSet
}

func (v *NullableAddProductFieldRequestUiVisibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddProductFieldRequestUiVisibility(val *AddProductFieldRequestUiVisibility) *NullableAddProductFieldRequestUiVisibility {
	return &NullableAddProductFieldRequestUiVisibility{value: val, isSet: true}
}

func (v NullableAddProductFieldRequestUiVisibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddProductFieldRequestUiVisibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


