/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetPersonFields200ResponseDataInnerRequiredFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPersonFields200ResponseDataInnerRequiredFields{}

// GetPersonFields200ResponseDataInnerRequiredFields Required fields configuration
type GetPersonFields200ResponseDataInnerRequiredFields struct {
	// Whether the field is required
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetPersonFields200ResponseDataInnerRequiredFields GetPersonFields200ResponseDataInnerRequiredFields

// NewGetPersonFields200ResponseDataInnerRequiredFields instantiates a new GetPersonFields200ResponseDataInnerRequiredFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPersonFields200ResponseDataInnerRequiredFields() *GetPersonFields200ResponseDataInnerRequiredFields {
	this := GetPersonFields200ResponseDataInnerRequiredFields{}
	return &this
}

// NewGetPersonFields200ResponseDataInnerRequiredFieldsWithDefaults instantiates a new GetPersonFields200ResponseDataInnerRequiredFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPersonFields200ResponseDataInnerRequiredFieldsWithDefaults() *GetPersonFields200ResponseDataInnerRequiredFields {
	this := GetPersonFields200ResponseDataInnerRequiredFields{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GetPersonFields200ResponseDataInnerRequiredFields) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonFields200ResponseDataInnerRequiredFields) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GetPersonFields200ResponseDataInnerRequiredFields) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GetPersonFields200ResponseDataInnerRequiredFields) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o GetPersonFields200ResponseDataInnerRequiredFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPersonFields200ResponseDataInnerRequiredFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPersonFields200ResponseDataInnerRequiredFields) UnmarshalJSON(data []byte) (err error) {
	varGetPersonFields200ResponseDataInnerRequiredFields := _GetPersonFields200ResponseDataInnerRequiredFields{}

	err = json.Unmarshal(data, &varGetPersonFields200ResponseDataInnerRequiredFields)

	if err != nil {
		return err
	}

	*o = GetPersonFields200ResponseDataInnerRequiredFields(varGetPersonFields200ResponseDataInnerRequiredFields)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPersonFields200ResponseDataInnerRequiredFields struct {
	value *GetPersonFields200ResponseDataInnerRequiredFields
	isSet bool
}

func (v NullableGetPersonFields200ResponseDataInnerRequiredFields) Get() *GetPersonFields200ResponseDataInnerRequiredFields {
	return v.value
}

func (v *NullableGetPersonFields200ResponseDataInnerRequiredFields) Set(val *GetPersonFields200ResponseDataInnerRequiredFields) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPersonFields200ResponseDataInnerRequiredFields) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPersonFields200ResponseDataInnerRequiredFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPersonFields200ResponseDataInnerRequiredFields(val *GetPersonFields200ResponseDataInnerRequiredFields) *NullableGetPersonFields200ResponseDataInnerRequiredFields {
	return &NullableGetPersonFields200ResponseDataInnerRequiredFields{value: val, isSet: true}
}

func (v NullableGetPersonFields200ResponseDataInnerRequiredFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPersonFields200ResponseDataInnerRequiredFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


