/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetItemSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetItemSearchResponse{}

// GetItemSearchResponse struct for GetItemSearchResponse
type GetItemSearchResponse struct {
	// If the response is successful or not
	Success              *bool                                   `json:"success,omitempty"`
	Data                 *GetItemSearchResponseDataData          `json:"data,omitempty"`
	AdditionalData       *GetDealsProductsResponseAdditionalData `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetItemSearchResponse GetItemSearchResponse

// NewGetItemSearchResponse instantiates a new GetItemSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetItemSearchResponse() *GetItemSearchResponse {
	this := GetItemSearchResponse{}
	return &this
}

// NewGetItemSearchResponseWithDefaults instantiates a new GetItemSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetItemSearchResponseWithDefaults() *GetItemSearchResponse {
	this := GetItemSearchResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetItemSearchResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetItemSearchResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetItemSearchResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetItemSearchResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetItemSearchResponse) GetData() GetItemSearchResponseDataData {
	if o == nil || IsNil(o.Data) {
		var ret GetItemSearchResponseDataData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetItemSearchResponse) GetDataOk() (*GetItemSearchResponseDataData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetItemSearchResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetItemSearchResponseDataData and assigns it to the Data field.
func (o *GetItemSearchResponse) SetData(v GetItemSearchResponseDataData) {
	o.Data = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetItemSearchResponse) GetAdditionalData() GetDealsProductsResponseAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetDealsProductsResponseAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetItemSearchResponse) GetAdditionalDataOk() (*GetDealsProductsResponseAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetItemSearchResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetDealsProductsResponseAdditionalData and assigns it to the AdditionalData field.
func (o *GetItemSearchResponse) SetAdditionalData(v GetDealsProductsResponseAdditionalData) {
	o.AdditionalData = &v
}

func (o GetItemSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetItemSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetItemSearchResponse) UnmarshalJSON(data []byte) (err error) {
	varGetItemSearchResponse := _GetItemSearchResponse{}

	err = json.Unmarshal(data, &varGetItemSearchResponse)

	if err != nil {
		return err
	}

	*o = GetItemSearchResponse(varGetItemSearchResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetItemSearchResponse struct {
	value *GetItemSearchResponse
	isSet bool
}

func (v NullableGetItemSearchResponse) Get() *GetItemSearchResponse {
	return v.value
}

func (v *NullableGetItemSearchResponse) Set(val *GetItemSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItemSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItemSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItemSearchResponse(val *GetItemSearchResponse) *NullableGetItemSearchResponse {
	return &NullableGetItemSearchResponse{value: val, isSet: true}
}

func (v NullableGetItemSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItemSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
