/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetActivityFields200ResponseDataInnerSubfieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetActivityFields200ResponseDataInnerSubfieldsInner{}

// GetActivityFields200ResponseDataInnerSubfieldsInner struct for GetActivityFields200ResponseDataInnerSubfieldsInner
type GetActivityFields200ResponseDataInnerSubfieldsInner struct {
	// The subfield identifier
	FieldCode *string `json:"field_code,omitempty"`
	// The subfield display name
	FieldName *string `json:"field_name,omitempty"`
	// The subfield type
	FieldType *string `json:"field_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetActivityFields200ResponseDataInnerSubfieldsInner GetActivityFields200ResponseDataInnerSubfieldsInner

// NewGetActivityFields200ResponseDataInnerSubfieldsInner instantiates a new GetActivityFields200ResponseDataInnerSubfieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetActivityFields200ResponseDataInnerSubfieldsInner() *GetActivityFields200ResponseDataInnerSubfieldsInner {
	this := GetActivityFields200ResponseDataInnerSubfieldsInner{}
	return &this
}

// NewGetActivityFields200ResponseDataInnerSubfieldsInnerWithDefaults instantiates a new GetActivityFields200ResponseDataInnerSubfieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetActivityFields200ResponseDataInnerSubfieldsInnerWithDefaults() *GetActivityFields200ResponseDataInnerSubfieldsInner {
	this := GetActivityFields200ResponseDataInnerSubfieldsInner{}
	return &this
}

// GetFieldCode returns the FieldCode field value if set, zero value otherwise.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) GetFieldCode() string {
	if o == nil || IsNil(o.FieldCode) {
		var ret string
		return ret
	}
	return *o.FieldCode
}

// GetFieldCodeOk returns a tuple with the FieldCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) GetFieldCodeOk() (*string, bool) {
	if o == nil || IsNil(o.FieldCode) {
		return nil, false
	}
	return o.FieldCode, true
}

// HasFieldCode returns a boolean if a field has been set.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) HasFieldCode() bool {
	if o != nil && !IsNil(o.FieldCode) {
		return true
	}

	return false
}

// SetFieldCode gets a reference to the given string and assigns it to the FieldCode field.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) SetFieldCode(v string) {
	o.FieldCode = &v
}

// GetFieldName returns the FieldName field value if set, zero value otherwise.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) GetFieldName() string {
	if o == nil || IsNil(o.FieldName) {
		var ret string
		return ret
	}
	return *o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) GetFieldNameOk() (*string, bool) {
	if o == nil || IsNil(o.FieldName) {
		return nil, false
	}
	return o.FieldName, true
}

// HasFieldName returns a boolean if a field has been set.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) HasFieldName() bool {
	if o != nil && !IsNil(o.FieldName) {
		return true
	}

	return false
}

// SetFieldName gets a reference to the given string and assigns it to the FieldName field.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) SetFieldName(v string) {
	o.FieldName = &v
}

// GetFieldType returns the FieldType field value if set, zero value otherwise.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) GetFieldType() string {
	if o == nil || IsNil(o.FieldType) {
		var ret string
		return ret
	}
	return *o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) GetFieldTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FieldType) {
		return nil, false
	}
	return o.FieldType, true
}

// HasFieldType returns a boolean if a field has been set.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) HasFieldType() bool {
	if o != nil && !IsNil(o.FieldType) {
		return true
	}

	return false
}

// SetFieldType gets a reference to the given string and assigns it to the FieldType field.
func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) SetFieldType(v string) {
	o.FieldType = &v
}

func (o GetActivityFields200ResponseDataInnerSubfieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActivityFields200ResponseDataInnerSubfieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldCode) {
		toSerialize["field_code"] = o.FieldCode
	}
	if !IsNil(o.FieldName) {
		toSerialize["field_name"] = o.FieldName
	}
	if !IsNil(o.FieldType) {
		toSerialize["field_type"] = o.FieldType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetActivityFields200ResponseDataInnerSubfieldsInner) UnmarshalJSON(data []byte) (err error) {
	varGetActivityFields200ResponseDataInnerSubfieldsInner := _GetActivityFields200ResponseDataInnerSubfieldsInner{}

	err = json.Unmarshal(data, &varGetActivityFields200ResponseDataInnerSubfieldsInner)

	if err != nil {
		return err
	}

	*o = GetActivityFields200ResponseDataInnerSubfieldsInner(varGetActivityFields200ResponseDataInnerSubfieldsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "field_code")
		delete(additionalProperties, "field_name")
		delete(additionalProperties, "field_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetActivityFields200ResponseDataInnerSubfieldsInner struct {
	value *GetActivityFields200ResponseDataInnerSubfieldsInner
	isSet bool
}

func (v NullableGetActivityFields200ResponseDataInnerSubfieldsInner) Get() *GetActivityFields200ResponseDataInnerSubfieldsInner {
	return v.value
}

func (v *NullableGetActivityFields200ResponseDataInnerSubfieldsInner) Set(val *GetActivityFields200ResponseDataInnerSubfieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActivityFields200ResponseDataInnerSubfieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActivityFields200ResponseDataInnerSubfieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActivityFields200ResponseDataInnerSubfieldsInner(val *GetActivityFields200ResponseDataInnerSubfieldsInner) *NullableGetActivityFields200ResponseDataInnerSubfieldsInner {
	return &NullableGetActivityFields200ResponseDataInnerSubfieldsInner{value: val, isSet: true}
}

func (v NullableGetActivityFields200ResponseDataInnerSubfieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActivityFields200ResponseDataInnerSubfieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


