/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the ItemSearchItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemSearchItem{}

// ItemSearchItem struct for ItemSearchItem
type ItemSearchItem struct {
	// Search result relevancy
	ResultScore *float32 `json:"result_score,omitempty"`
	// Item
	Item                 map[string]interface{} `json:"item,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ItemSearchItem ItemSearchItem

// NewItemSearchItem instantiates a new ItemSearchItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemSearchItem() *ItemSearchItem {
	this := ItemSearchItem{}
	return &this
}

// NewItemSearchItemWithDefaults instantiates a new ItemSearchItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemSearchItemWithDefaults() *ItemSearchItem {
	this := ItemSearchItem{}
	return &this
}

// GetResultScore returns the ResultScore field value if set, zero value otherwise.
func (o *ItemSearchItem) GetResultScore() float32 {
	if o == nil || IsNil(o.ResultScore) {
		var ret float32
		return ret
	}
	return *o.ResultScore
}

// GetResultScoreOk returns a tuple with the ResultScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemSearchItem) GetResultScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.ResultScore) {
		return nil, false
	}
	return o.ResultScore, true
}

// HasResultScore returns a boolean if a field has been set.
func (o *ItemSearchItem) HasResultScore() bool {
	if o != nil && !IsNil(o.ResultScore) {
		return true
	}

	return false
}

// SetResultScore gets a reference to the given float32 and assigns it to the ResultScore field.
func (o *ItemSearchItem) SetResultScore(v float32) {
	o.ResultScore = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *ItemSearchItem) GetItem() map[string]interface{} {
	if o == nil || IsNil(o.Item) {
		var ret map[string]interface{}
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemSearchItem) GetItemOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Item) {
		return map[string]interface{}{}, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *ItemSearchItem) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given map[string]interface{} and assigns it to the Item field.
func (o *ItemSearchItem) SetItem(v map[string]interface{}) {
	o.Item = v
}

func (o ItemSearchItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemSearchItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResultScore) {
		toSerialize["result_score"] = o.ResultScore
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ItemSearchItem) UnmarshalJSON(data []byte) (err error) {
	varItemSearchItem := _ItemSearchItem{}

	err = json.Unmarshal(data, &varItemSearchItem)

	if err != nil {
		return err
	}

	*o = ItemSearchItem(varItemSearchItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result_score")
		delete(additionalProperties, "item")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableItemSearchItem struct {
	value *ItemSearchItem
	isSet bool
}

func (v NullableItemSearchItem) Get() *ItemSearchItem {
	return v.value
}

func (v *NullableItemSearchItem) Set(val *ItemSearchItem) {
	v.value = val
	v.isSet = true
}

func (v NullableItemSearchItem) IsSet() bool {
	return v.isSet
}

func (v *NullableItemSearchItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemSearchItem(val *ItemSearchItem) *NullableItemSearchItem {
	return &NullableItemSearchItem{value: val, isSet: true}
}

func (v NullableItemSearchItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemSearchItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
