/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetProductVariationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProductVariationsResponse{}

// GetProductVariationsResponse struct for GetProductVariationsResponse
type GetProductVariationsResponse struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	// Array containing data for all products
	Data                 []GetProductVariationsResponseDataInner `json:"data,omitempty"`
	AdditionalData       *GetDealsProductsResponseAdditionalData `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetProductVariationsResponse GetProductVariationsResponse

// NewGetProductVariationsResponse instantiates a new GetProductVariationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProductVariationsResponse() *GetProductVariationsResponse {
	this := GetProductVariationsResponse{}
	return &this
}

// NewGetProductVariationsResponseWithDefaults instantiates a new GetProductVariationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProductVariationsResponseWithDefaults() *GetProductVariationsResponse {
	this := GetProductVariationsResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetProductVariationsResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductVariationsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetProductVariationsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetProductVariationsResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetProductVariationsResponse) GetData() []GetProductVariationsResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetProductVariationsResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductVariationsResponse) GetDataOk() ([]GetProductVariationsResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetProductVariationsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetProductVariationsResponseDataInner and assigns it to the Data field.
func (o *GetProductVariationsResponse) SetData(v []GetProductVariationsResponseDataInner) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetProductVariationsResponse) GetAdditionalData() GetDealsProductsResponseAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetDealsProductsResponseAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductVariationsResponse) GetAdditionalDataOk() (*GetDealsProductsResponseAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetProductVariationsResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetDealsProductsResponseAdditionalData and assigns it to the AdditionalData field.
func (o *GetProductVariationsResponse) SetAdditionalData(v GetDealsProductsResponseAdditionalData) {
	o.AdditionalData = &v
}

func (o GetProductVariationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProductVariationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProductVariationsResponse) UnmarshalJSON(data []byte) (err error) {
	varGetProductVariationsResponse := _GetProductVariationsResponse{}

	err = json.Unmarshal(data, &varGetProductVariationsResponse)

	if err != nil {
		return err
	}

	*o = GetProductVariationsResponse(varGetProductVariationsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProductVariationsResponse struct {
	value *GetProductVariationsResponse
	isSet bool
}

func (v NullableGetProductVariationsResponse) Get() *GetProductVariationsResponse {
	return v.value
}

func (v *NullableGetProductVariationsResponse) Set(val *GetProductVariationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProductVariationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProductVariationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProductVariationsResponse(val *GetProductVariationsResponse) *NullableGetProductVariationsResponse {
	return &NullableGetProductVariationsResponse{value: val, isSet: true}
}

func (v NullableGetProductVariationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProductVariationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
