/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetDealSearchResponseAllOfDataItemsInnerItemStage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDealSearchResponseAllOfDataItemsInnerItemStage{}

// GetDealSearchResponseAllOfDataItemsInnerItemStage struct for GetDealSearchResponseAllOfDataItemsInnerItemStage
type GetDealSearchResponseAllOfDataItemsInnerItemStage struct {
	// The ID of the stage of the deal
	Id *int32 `json:"id,omitempty"`
	// The name of the stage of the deal
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetDealSearchResponseAllOfDataItemsInnerItemStage GetDealSearchResponseAllOfDataItemsInnerItemStage

// NewGetDealSearchResponseAllOfDataItemsInnerItemStage instantiates a new GetDealSearchResponseAllOfDataItemsInnerItemStage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDealSearchResponseAllOfDataItemsInnerItemStage() *GetDealSearchResponseAllOfDataItemsInnerItemStage {
	this := GetDealSearchResponseAllOfDataItemsInnerItemStage{}
	return &this
}

// NewGetDealSearchResponseAllOfDataItemsInnerItemStageWithDefaults instantiates a new GetDealSearchResponseAllOfDataItemsInnerItemStage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDealSearchResponseAllOfDataItemsInnerItemStageWithDefaults() *GetDealSearchResponseAllOfDataItemsInnerItemStage {
	this := GetDealSearchResponseAllOfDataItemsInnerItemStage{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) SetName(v string) {
	o.Name = &v
}

func (o GetDealSearchResponseAllOfDataItemsInnerItemStage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDealSearchResponseAllOfDataItemsInnerItemStage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDealSearchResponseAllOfDataItemsInnerItemStage) UnmarshalJSON(data []byte) (err error) {
	varGetDealSearchResponseAllOfDataItemsInnerItemStage := _GetDealSearchResponseAllOfDataItemsInnerItemStage{}

	err = json.Unmarshal(data, &varGetDealSearchResponseAllOfDataItemsInnerItemStage)

	if err != nil {
		return err
	}

	*o = GetDealSearchResponseAllOfDataItemsInnerItemStage(varGetDealSearchResponseAllOfDataItemsInnerItemStage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDealSearchResponseAllOfDataItemsInnerItemStage struct {
	value *GetDealSearchResponseAllOfDataItemsInnerItemStage
	isSet bool
}

func (v NullableGetDealSearchResponseAllOfDataItemsInnerItemStage) Get() *GetDealSearchResponseAllOfDataItemsInnerItemStage {
	return v.value
}

func (v *NullableGetDealSearchResponseAllOfDataItemsInnerItemStage) Set(val *GetDealSearchResponseAllOfDataItemsInnerItemStage) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDealSearchResponseAllOfDataItemsInnerItemStage) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDealSearchResponseAllOfDataItemsInnerItemStage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDealSearchResponseAllOfDataItemsInnerItemStage(val *GetDealSearchResponseAllOfDataItemsInnerItemStage) *NullableGetDealSearchResponseAllOfDataItemsInnerItemStage {
	return &NullableGetDealSearchResponseAllOfDataItemsInnerItemStage{value: val, isSet: true}
}

func (v NullableGetDealSearchResponseAllOfDataItemsInnerItemStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDealSearchResponseAllOfDataItemsInnerItemStage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
