/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetOrganizationSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationSearchResponse{}

// GetOrganizationSearchResponse struct for GetOrganizationSearchResponse
type GetOrganizationSearchResponse struct {
	// If the response is successful or not
	Success              *bool                                   `json:"success,omitempty"`
	Data                 *GetOrganizationSearchResponseAllOfData `json:"data,omitempty"`
	AdditionalData       *GetDealsProductsResponseAdditionalData `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetOrganizationSearchResponse GetOrganizationSearchResponse

// NewGetOrganizationSearchResponse instantiates a new GetOrganizationSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationSearchResponse() *GetOrganizationSearchResponse {
	this := GetOrganizationSearchResponse{}
	return &this
}

// NewGetOrganizationSearchResponseWithDefaults instantiates a new GetOrganizationSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationSearchResponseWithDefaults() *GetOrganizationSearchResponse {
	this := GetOrganizationSearchResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetOrganizationSearchResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationSearchResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetOrganizationSearchResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetOrganizationSearchResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetOrganizationSearchResponse) GetData() GetOrganizationSearchResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret GetOrganizationSearchResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationSearchResponse) GetDataOk() (*GetOrganizationSearchResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetOrganizationSearchResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetOrganizationSearchResponseAllOfData and assigns it to the Data field.
func (o *GetOrganizationSearchResponse) SetData(v GetOrganizationSearchResponseAllOfData) {
	o.Data = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetOrganizationSearchResponse) GetAdditionalData() GetDealsProductsResponseAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetDealsProductsResponseAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationSearchResponse) GetAdditionalDataOk() (*GetDealsProductsResponseAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetOrganizationSearchResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetDealsProductsResponseAdditionalData and assigns it to the AdditionalData field.
func (o *GetOrganizationSearchResponse) SetAdditionalData(v GetDealsProductsResponseAdditionalData) {
	o.AdditionalData = &v
}

func (o GetOrganizationSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetOrganizationSearchResponse) UnmarshalJSON(data []byte) (err error) {
	varGetOrganizationSearchResponse := _GetOrganizationSearchResponse{}

	err = json.Unmarshal(data, &varGetOrganizationSearchResponse)

	if err != nil {
		return err
	}

	*o = GetOrganizationSearchResponse(varGetOrganizationSearchResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetOrganizationSearchResponse struct {
	value *GetOrganizationSearchResponse
	isSet bool
}

func (v NullableGetOrganizationSearchResponse) Get() *GetOrganizationSearchResponse {
	return v.value
}

func (v *NullableGetOrganizationSearchResponse) Set(val *GetOrganizationSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationSearchResponse(val *GetOrganizationSearchResponse) *NullableGetOrganizationSearchResponse {
	return &NullableGetOrganizationSearchResponse{value: val, isSet: true}
}

func (v NullableGetOrganizationSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
