/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetPersonSearchResponseAllOfDataItemsInnerItemOwner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPersonSearchResponseAllOfDataItemsInnerItemOwner{}

// GetPersonSearchResponseAllOfDataItemsInnerItemOwner struct for GetPersonSearchResponseAllOfDataItemsInnerItemOwner
type GetPersonSearchResponseAllOfDataItemsInnerItemOwner struct {
	// The ID of the owner of the person
	Id *int32 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetPersonSearchResponseAllOfDataItemsInnerItemOwner GetPersonSearchResponseAllOfDataItemsInnerItemOwner

// NewGetPersonSearchResponseAllOfDataItemsInnerItemOwner instantiates a new GetPersonSearchResponseAllOfDataItemsInnerItemOwner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPersonSearchResponseAllOfDataItemsInnerItemOwner() *GetPersonSearchResponseAllOfDataItemsInnerItemOwner {
	this := GetPersonSearchResponseAllOfDataItemsInnerItemOwner{}
	return &this
}

// NewGetPersonSearchResponseAllOfDataItemsInnerItemOwnerWithDefaults instantiates a new GetPersonSearchResponseAllOfDataItemsInnerItemOwner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPersonSearchResponseAllOfDataItemsInnerItemOwnerWithDefaults() *GetPersonSearchResponseAllOfDataItemsInnerItemOwner {
	this := GetPersonSearchResponseAllOfDataItemsInnerItemOwner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) SetId(v int32) {
	o.Id = &v
}

func (o GetPersonSearchResponseAllOfDataItemsInnerItemOwner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPersonSearchResponseAllOfDataItemsInnerItemOwner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) UnmarshalJSON(data []byte) (err error) {
	varGetPersonSearchResponseAllOfDataItemsInnerItemOwner := _GetPersonSearchResponseAllOfDataItemsInnerItemOwner{}

	err = json.Unmarshal(data, &varGetPersonSearchResponseAllOfDataItemsInnerItemOwner)

	if err != nil {
		return err
	}

	*o = GetPersonSearchResponseAllOfDataItemsInnerItemOwner(varGetPersonSearchResponseAllOfDataItemsInnerItemOwner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner struct {
	value *GetPersonSearchResponseAllOfDataItemsInnerItemOwner
	isSet bool
}

func (v NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner) Get() *GetPersonSearchResponseAllOfDataItemsInnerItemOwner {
	return v.value
}

func (v *NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner) Set(val *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner(val *GetPersonSearchResponseAllOfDataItemsInnerItemOwner) *NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner {
	return &NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner{value: val, isSet: true}
}

func (v NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPersonSearchResponseAllOfDataItemsInnerItemOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


