/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetDealSearchResponseAllOfDataItemsInnerItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDealSearchResponseAllOfDataItemsInnerItem{}

// GetDealSearchResponseAllOfDataItemsInnerItem struct for GetDealSearchResponseAllOfDataItemsInnerItem
type GetDealSearchResponseAllOfDataItemsInnerItem struct {
	// The ID of the deal
	Id *int32 `json:"id,omitempty"`
	// The type of the item
	Type *string `json:"type,omitempty"`
	// The title of the deal
	Title *string `json:"title,omitempty"`
	// The value of the deal
	Value *int32 `json:"value,omitempty"`
	// The currency of the deal
	Currency *string `json:"currency,omitempty"`
	// The status of the deal
	Status *string `json:"status,omitempty"`
	// The visibility of the deal
	VisibleTo *int32 `json:"visible_to,omitempty"`
	Owner *GetDealSearchResponseAllOfDataItemsInnerItemOwner `json:"owner,omitempty"`
	Stage *GetDealSearchResponseAllOfDataItemsInnerItemStage `json:"stage,omitempty"`
	Person NullableGetDealSearchResponseAllOfDataItemsInnerItemPerson `json:"person,omitempty"`
	Organization NullableGetDealSearchResponseAllOfDataItemsInnerItemOrganization `json:"organization,omitempty"`
	// Custom fields
	CustomFields []string `json:"custom_fields,omitempty"`
	// An array of notes
	Notes []string `json:"notes,omitempty"`
	// A flag indicating whether the deal is archived or not
	IsArchived *bool `json:"is_archived,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetDealSearchResponseAllOfDataItemsInnerItem GetDealSearchResponseAllOfDataItemsInnerItem

// NewGetDealSearchResponseAllOfDataItemsInnerItem instantiates a new GetDealSearchResponseAllOfDataItemsInnerItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDealSearchResponseAllOfDataItemsInnerItem() *GetDealSearchResponseAllOfDataItemsInnerItem {
	this := GetDealSearchResponseAllOfDataItemsInnerItem{}
	return &this
}

// NewGetDealSearchResponseAllOfDataItemsInnerItemWithDefaults instantiates a new GetDealSearchResponseAllOfDataItemsInnerItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDealSearchResponseAllOfDataItemsInnerItemWithDefaults() *GetDealSearchResponseAllOfDataItemsInnerItem {
	this := GetDealSearchResponseAllOfDataItemsInnerItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetId(v int32) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetTitle(v string) {
	o.Title = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetValue(v int32) {
	o.Value = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetCurrency(v string) {
	o.Currency = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetStatus(v string) {
	o.Status = &v
}

// GetVisibleTo returns the VisibleTo field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetVisibleTo() int32 {
	if o == nil || IsNil(o.VisibleTo) {
		var ret int32
		return ret
	}
	return *o.VisibleTo
}

// GetVisibleToOk returns a tuple with the VisibleTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetVisibleToOk() (*int32, bool) {
	if o == nil || IsNil(o.VisibleTo) {
		return nil, false
	}
	return o.VisibleTo, true
}

// HasVisibleTo returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasVisibleTo() bool {
	if o != nil && !IsNil(o.VisibleTo) {
		return true
	}

	return false
}

// SetVisibleTo gets a reference to the given int32 and assigns it to the VisibleTo field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetVisibleTo(v int32) {
	o.VisibleTo = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetOwner() GetDealSearchResponseAllOfDataItemsInnerItemOwner {
	if o == nil || IsNil(o.Owner) {
		var ret GetDealSearchResponseAllOfDataItemsInnerItemOwner
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetOwnerOk() (*GetDealSearchResponseAllOfDataItemsInnerItemOwner, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given GetDealSearchResponseAllOfDataItemsInnerItemOwner and assigns it to the Owner field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetOwner(v GetDealSearchResponseAllOfDataItemsInnerItemOwner) {
	o.Owner = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetStage() GetDealSearchResponseAllOfDataItemsInnerItemStage {
	if o == nil || IsNil(o.Stage) {
		var ret GetDealSearchResponseAllOfDataItemsInnerItemStage
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetStageOk() (*GetDealSearchResponseAllOfDataItemsInnerItemStage, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given GetDealSearchResponseAllOfDataItemsInnerItemStage and assigns it to the Stage field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetStage(v GetDealSearchResponseAllOfDataItemsInnerItemStage) {
	o.Stage = &v
}

// GetPerson returns the Person field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetPerson() GetDealSearchResponseAllOfDataItemsInnerItemPerson {
	if o == nil || IsNil(o.Person.Get()) {
		var ret GetDealSearchResponseAllOfDataItemsInnerItemPerson
		return ret
	}
	return *o.Person.Get()
}

// GetPersonOk returns a tuple with the Person field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetPersonOk() (*GetDealSearchResponseAllOfDataItemsInnerItemPerson, bool) {
	if o == nil {
		return nil, false
	}
	return o.Person.Get(), o.Person.IsSet()
}

// HasPerson returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasPerson() bool {
	if o != nil && o.Person.IsSet() {
		return true
	}

	return false
}

// SetPerson gets a reference to the given NullableGetDealSearchResponseAllOfDataItemsInnerItemPerson and assigns it to the Person field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetPerson(v GetDealSearchResponseAllOfDataItemsInnerItemPerson) {
	o.Person.Set(&v)
}
// SetPersonNil sets the value for Person to be an explicit nil
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetPersonNil() {
	o.Person.Set(nil)
}

// UnsetPerson ensures that no value is present for Person, not even an explicit nil
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) UnsetPerson() {
	o.Person.Unset()
}

// GetOrganization returns the Organization field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetOrganization() GetDealSearchResponseAllOfDataItemsInnerItemOrganization {
	if o == nil || IsNil(o.Organization.Get()) {
		var ret GetDealSearchResponseAllOfDataItemsInnerItemOrganization
		return ret
	}
	return *o.Organization.Get()
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetOrganizationOk() (*GetDealSearchResponseAllOfDataItemsInnerItemOrganization, bool) {
	if o == nil {
		return nil, false
	}
	return o.Organization.Get(), o.Organization.IsSet()
}

// HasOrganization returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasOrganization() bool {
	if o != nil && o.Organization.IsSet() {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given NullableGetDealSearchResponseAllOfDataItemsInnerItemOrganization and assigns it to the Organization field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetOrganization(v GetDealSearchResponseAllOfDataItemsInnerItemOrganization) {
	o.Organization.Set(&v)
}
// SetOrganizationNil sets the value for Organization to be an explicit nil
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetOrganizationNil() {
	o.Organization.Set(nil)
}

// UnsetOrganization ensures that no value is present for Organization, not even an explicit nil
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) UnsetOrganization() {
	o.Organization.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetCustomFields() []string {
	if o == nil || IsNil(o.CustomFields) {
		var ret []string
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetCustomFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given []string and assigns it to the CustomFields field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetCustomFields(v []string) {
	o.CustomFields = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetNotes(v []string) {
	o.Notes = v
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived) {
		var ret bool
		return ret
	}
	return *o.IsArchived
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) GetIsArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArchived) {
		return nil, false
	}
	return o.IsArchived, true
}

// HasIsArchived returns a boolean if a field has been set.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) HasIsArchived() bool {
	if o != nil && !IsNil(o.IsArchived) {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given bool and assigns it to the IsArchived field.
func (o *GetDealSearchResponseAllOfDataItemsInnerItem) SetIsArchived(v bool) {
	o.IsArchived = &v
}

func (o GetDealSearchResponseAllOfDataItemsInnerItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDealSearchResponseAllOfDataItemsInnerItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.VisibleTo) {
		toSerialize["visible_to"] = o.VisibleTo
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	if o.Person.IsSet() {
		toSerialize["person"] = o.Person.Get()
	}
	if o.Organization.IsSet() {
		toSerialize["organization"] = o.Organization.Get()
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.IsArchived) {
		toSerialize["is_archived"] = o.IsArchived
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDealSearchResponseAllOfDataItemsInnerItem) UnmarshalJSON(data []byte) (err error) {
	varGetDealSearchResponseAllOfDataItemsInnerItem := _GetDealSearchResponseAllOfDataItemsInnerItem{}

	err = json.Unmarshal(data, &varGetDealSearchResponseAllOfDataItemsInnerItem)

	if err != nil {
		return err
	}

	*o = GetDealSearchResponseAllOfDataItemsInnerItem(varGetDealSearchResponseAllOfDataItemsInnerItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "title")
		delete(additionalProperties, "value")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "status")
		delete(additionalProperties, "visible_to")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "stage")
		delete(additionalProperties, "person")
		delete(additionalProperties, "organization")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "is_archived")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDealSearchResponseAllOfDataItemsInnerItem struct {
	value *GetDealSearchResponseAllOfDataItemsInnerItem
	isSet bool
}

func (v NullableGetDealSearchResponseAllOfDataItemsInnerItem) Get() *GetDealSearchResponseAllOfDataItemsInnerItem {
	return v.value
}

func (v *NullableGetDealSearchResponseAllOfDataItemsInnerItem) Set(val *GetDealSearchResponseAllOfDataItemsInnerItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDealSearchResponseAllOfDataItemsInnerItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDealSearchResponseAllOfDataItemsInnerItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDealSearchResponseAllOfDataItemsInnerItem(val *GetDealSearchResponseAllOfDataItemsInnerItem) *NullableGetDealSearchResponseAllOfDataItemsInnerItem {
	return &NullableGetDealSearchResponseAllOfDataItemsInnerItem{value: val, isSet: true}
}

func (v NullableGetDealSearchResponseAllOfDataItemsInnerItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDealSearchResponseAllOfDataItemsInnerItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


