/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the AddProjectFieldRequestRequiredFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddProjectFieldRequestRequiredFields{}

// AddProjectFieldRequestRequiredFields Required fields configuration for marking the field as mandatory when interacted with in the Pipedrive web UI.
type AddProjectFieldRequestRequiredFields struct {
	// Whether the field is required. When false, the field is optional. When true, the field is required when creating or updating projects. Default is false.
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddProjectFieldRequestRequiredFields AddProjectFieldRequestRequiredFields

// NewAddProjectFieldRequestRequiredFields instantiates a new AddProjectFieldRequestRequiredFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddProjectFieldRequestRequiredFields() *AddProjectFieldRequestRequiredFields {
	this := AddProjectFieldRequestRequiredFields{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewAddProjectFieldRequestRequiredFieldsWithDefaults instantiates a new AddProjectFieldRequestRequiredFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddProjectFieldRequestRequiredFieldsWithDefaults() *AddProjectFieldRequestRequiredFields {
	this := AddProjectFieldRequestRequiredFields{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AddProjectFieldRequestRequiredFields) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddProjectFieldRequestRequiredFields) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AddProjectFieldRequestRequiredFields) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AddProjectFieldRequestRequiredFields) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o AddProjectFieldRequestRequiredFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddProjectFieldRequestRequiredFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddProjectFieldRequestRequiredFields) UnmarshalJSON(data []byte) (err error) {
	varAddProjectFieldRequestRequiredFields := _AddProjectFieldRequestRequiredFields{}

	err = json.Unmarshal(data, &varAddProjectFieldRequestRequiredFields)

	if err != nil {
		return err
	}

	*o = AddProjectFieldRequestRequiredFields(varAddProjectFieldRequestRequiredFields)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddProjectFieldRequestRequiredFields struct {
	value *AddProjectFieldRequestRequiredFields
	isSet bool
}

func (v NullableAddProjectFieldRequestRequiredFields) Get() *AddProjectFieldRequestRequiredFields {
	return v.value
}

func (v *NullableAddProjectFieldRequestRequiredFields) Set(val *AddProjectFieldRequestRequiredFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAddProjectFieldRequestRequiredFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAddProjectFieldRequestRequiredFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddProjectFieldRequestRequiredFields(val *AddProjectFieldRequestRequiredFields) *NullableAddProjectFieldRequestRequiredFields {
	return &NullableAddProjectFieldRequestRequiredFields{value: val, isSet: true}
}

func (v NullableAddProjectFieldRequestRequiredFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddProjectFieldRequestRequiredFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


