/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetDealsProductsResponseAdditionalData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDealsProductsResponseAdditionalData{}

// GetDealsProductsResponseAdditionalData Pagination related data
type GetDealsProductsResponseAdditionalData struct {
	// The first item on the next page. The value of the `next_cursor` field will be `null` if you have reached the end of the dataset and there’s no more pages to be returned.
	NextCursor           *string `json:"next_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetDealsProductsResponseAdditionalData GetDealsProductsResponseAdditionalData

// NewGetDealsProductsResponseAdditionalData instantiates a new GetDealsProductsResponseAdditionalData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDealsProductsResponseAdditionalData() *GetDealsProductsResponseAdditionalData {
	this := GetDealsProductsResponseAdditionalData{}
	return &this
}

// NewGetDealsProductsResponseAdditionalDataWithDefaults instantiates a new GetDealsProductsResponseAdditionalData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDealsProductsResponseAdditionalDataWithDefaults() *GetDealsProductsResponseAdditionalData {
	this := GetDealsProductsResponseAdditionalData{}
	return &this
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *GetDealsProductsResponseAdditionalData) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealsProductsResponseAdditionalData) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *GetDealsProductsResponseAdditionalData) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *GetDealsProductsResponseAdditionalData) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o GetDealsProductsResponseAdditionalData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDealsProductsResponseAdditionalData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDealsProductsResponseAdditionalData) UnmarshalJSON(data []byte) (err error) {
	varGetDealsProductsResponseAdditionalData := _GetDealsProductsResponseAdditionalData{}

	err = json.Unmarshal(data, &varGetDealsProductsResponseAdditionalData)

	if err != nil {
		return err
	}

	*o = GetDealsProductsResponseAdditionalData(varGetDealsProductsResponseAdditionalData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDealsProductsResponseAdditionalData struct {
	value *GetDealsProductsResponseAdditionalData
	isSet bool
}

func (v NullableGetDealsProductsResponseAdditionalData) Get() *GetDealsProductsResponseAdditionalData {
	return v.value
}

func (v *NullableGetDealsProductsResponseAdditionalData) Set(val *GetDealsProductsResponseAdditionalData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDealsProductsResponseAdditionalData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDealsProductsResponseAdditionalData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDealsProductsResponseAdditionalData(val *GetDealsProductsResponseAdditionalData) *NullableGetDealsProductsResponseAdditionalData {
	return &NullableGetDealsProductsResponseAdditionalData{value: val, isSet: true}
}

func (v NullableGetDealsProductsResponseAdditionalData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDealsProductsResponseAdditionalData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
