/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the AddActivityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddActivityRequest{}

// AddActivityRequest struct for AddActivityRequest
type AddActivityRequest struct {
	// The subject of the activity
	Subject *string `json:"subject,omitempty"`
	// The type of the activity
	Type *string `json:"type,omitempty"`
	// The ID of the user who owns the activity
	OwnerId *int32 `json:"owner_id,omitempty"`
	// The ID of the deal linked to the activity
	DealId *int32 `json:"deal_id,omitempty"`
	// The ID of the lead linked to the activity
	LeadId *string `json:"lead_id,omitempty"`
	// The ID of the person linked to the activity
	PersonId *int32 `json:"person_id,omitempty"`
	// The ID of the organization linked to the activity
	OrgId *int32 `json:"org_id,omitempty"`
	// The ID of the project linked to the activity
	ProjectId *int32 `json:"project_id,omitempty"`
	// The due date of the activity
	DueDate *string `json:"due_date,omitempty"`
	// The due time of the activity
	DueTime *string `json:"due_time,omitempty"`
	// The duration of the activity
	Duration *string `json:"duration,omitempty"`
	// Whether the activity marks the assignee as busy or not in their calendar
	Busy *bool `json:"busy,omitempty"`
	// Whether the activity is marked as done or not
	Done *bool `json:"done,omitempty"`
	Location *GetActivitiesResponseAllOfDataInnerLocation `json:"location,omitempty"`
	// The participants of the activity
	Participants []GetActivitiesResponseAllOfDataInnerParticipantsInner `json:"participants,omitempty"`
	// The attendees of the activity
	Attendees []GetActivitiesResponseAllOfDataInnerAttendeesInner `json:"attendees,omitempty"`
	// The public description of the activity
	PublicDescription *string `json:"public_description,omitempty"`
	// The priority of the activity. Mappable to a specific string using activityFields API.
	Priority *int32 `json:"priority,omitempty"`
	// The note of the activity
	Note *string `json:"note,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddActivityRequest AddActivityRequest

// NewAddActivityRequest instantiates a new AddActivityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddActivityRequest() *AddActivityRequest {
	this := AddActivityRequest{}
	return &this
}

// NewAddActivityRequestWithDefaults instantiates a new AddActivityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddActivityRequestWithDefaults() *AddActivityRequest {
	this := AddActivityRequest{}
	return &this
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *AddActivityRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *AddActivityRequest) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *AddActivityRequest) SetSubject(v string) {
	o.Subject = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AddActivityRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AddActivityRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AddActivityRequest) SetType(v string) {
	o.Type = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *AddActivityRequest) GetOwnerId() int32 {
	if o == nil || IsNil(o.OwnerId) {
		var ret int32
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetOwnerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *AddActivityRequest) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given int32 and assigns it to the OwnerId field.
func (o *AddActivityRequest) SetOwnerId(v int32) {
	o.OwnerId = &v
}

// GetDealId returns the DealId field value if set, zero value otherwise.
func (o *AddActivityRequest) GetDealId() int32 {
	if o == nil || IsNil(o.DealId) {
		var ret int32
		return ret
	}
	return *o.DealId
}

// GetDealIdOk returns a tuple with the DealId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetDealIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DealId) {
		return nil, false
	}
	return o.DealId, true
}

// HasDealId returns a boolean if a field has been set.
func (o *AddActivityRequest) HasDealId() bool {
	if o != nil && !IsNil(o.DealId) {
		return true
	}

	return false
}

// SetDealId gets a reference to the given int32 and assigns it to the DealId field.
func (o *AddActivityRequest) SetDealId(v int32) {
	o.DealId = &v
}

// GetLeadId returns the LeadId field value if set, zero value otherwise.
func (o *AddActivityRequest) GetLeadId() string {
	if o == nil || IsNil(o.LeadId) {
		var ret string
		return ret
	}
	return *o.LeadId
}

// GetLeadIdOk returns a tuple with the LeadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetLeadIdOk() (*string, bool) {
	if o == nil || IsNil(o.LeadId) {
		return nil, false
	}
	return o.LeadId, true
}

// HasLeadId returns a boolean if a field has been set.
func (o *AddActivityRequest) HasLeadId() bool {
	if o != nil && !IsNil(o.LeadId) {
		return true
	}

	return false
}

// SetLeadId gets a reference to the given string and assigns it to the LeadId field.
func (o *AddActivityRequest) SetLeadId(v string) {
	o.LeadId = &v
}

// GetPersonId returns the PersonId field value if set, zero value otherwise.
func (o *AddActivityRequest) GetPersonId() int32 {
	if o == nil || IsNil(o.PersonId) {
		var ret int32
		return ret
	}
	return *o.PersonId
}

// GetPersonIdOk returns a tuple with the PersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetPersonIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PersonId) {
		return nil, false
	}
	return o.PersonId, true
}

// HasPersonId returns a boolean if a field has been set.
func (o *AddActivityRequest) HasPersonId() bool {
	if o != nil && !IsNil(o.PersonId) {
		return true
	}

	return false
}

// SetPersonId gets a reference to the given int32 and assigns it to the PersonId field.
func (o *AddActivityRequest) SetPersonId(v int32) {
	o.PersonId = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *AddActivityRequest) GetOrgId() int32 {
	if o == nil || IsNil(o.OrgId) {
		var ret int32
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetOrgIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *AddActivityRequest) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given int32 and assigns it to the OrgId field.
func (o *AddActivityRequest) SetOrgId(v int32) {
	o.OrgId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *AddActivityRequest) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *AddActivityRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *AddActivityRequest) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *AddActivityRequest) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *AddActivityRequest) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *AddActivityRequest) SetDueDate(v string) {
	o.DueDate = &v
}

// GetDueTime returns the DueTime field value if set, zero value otherwise.
func (o *AddActivityRequest) GetDueTime() string {
	if o == nil || IsNil(o.DueTime) {
		var ret string
		return ret
	}
	return *o.DueTime
}

// GetDueTimeOk returns a tuple with the DueTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetDueTimeOk() (*string, bool) {
	if o == nil || IsNil(o.DueTime) {
		return nil, false
	}
	return o.DueTime, true
}

// HasDueTime returns a boolean if a field has been set.
func (o *AddActivityRequest) HasDueTime() bool {
	if o != nil && !IsNil(o.DueTime) {
		return true
	}

	return false
}

// SetDueTime gets a reference to the given string and assigns it to the DueTime field.
func (o *AddActivityRequest) SetDueTime(v string) {
	o.DueTime = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *AddActivityRequest) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *AddActivityRequest) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *AddActivityRequest) SetDuration(v string) {
	o.Duration = &v
}

// GetBusy returns the Busy field value if set, zero value otherwise.
func (o *AddActivityRequest) GetBusy() bool {
	if o == nil || IsNil(o.Busy) {
		var ret bool
		return ret
	}
	return *o.Busy
}

// GetBusyOk returns a tuple with the Busy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetBusyOk() (*bool, bool) {
	if o == nil || IsNil(o.Busy) {
		return nil, false
	}
	return o.Busy, true
}

// HasBusy returns a boolean if a field has been set.
func (o *AddActivityRequest) HasBusy() bool {
	if o != nil && !IsNil(o.Busy) {
		return true
	}

	return false
}

// SetBusy gets a reference to the given bool and assigns it to the Busy field.
func (o *AddActivityRequest) SetBusy(v bool) {
	o.Busy = &v
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *AddActivityRequest) GetDone() bool {
	if o == nil || IsNil(o.Done) {
		var ret bool
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetDoneOk() (*bool, bool) {
	if o == nil || IsNil(o.Done) {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *AddActivityRequest) HasDone() bool {
	if o != nil && !IsNil(o.Done) {
		return true
	}

	return false
}

// SetDone gets a reference to the given bool and assigns it to the Done field.
func (o *AddActivityRequest) SetDone(v bool) {
	o.Done = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *AddActivityRequest) GetLocation() GetActivitiesResponseAllOfDataInnerLocation {
	if o == nil || IsNil(o.Location) {
		var ret GetActivitiesResponseAllOfDataInnerLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetLocationOk() (*GetActivitiesResponseAllOfDataInnerLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *AddActivityRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given GetActivitiesResponseAllOfDataInnerLocation and assigns it to the Location field.
func (o *AddActivityRequest) SetLocation(v GetActivitiesResponseAllOfDataInnerLocation) {
	o.Location = &v
}

// GetParticipants returns the Participants field value if set, zero value otherwise.
func (o *AddActivityRequest) GetParticipants() []GetActivitiesResponseAllOfDataInnerParticipantsInner {
	if o == nil || IsNil(o.Participants) {
		var ret []GetActivitiesResponseAllOfDataInnerParticipantsInner
		return ret
	}
	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetParticipantsOk() ([]GetActivitiesResponseAllOfDataInnerParticipantsInner, bool) {
	if o == nil || IsNil(o.Participants) {
		return nil, false
	}
	return o.Participants, true
}

// HasParticipants returns a boolean if a field has been set.
func (o *AddActivityRequest) HasParticipants() bool {
	if o != nil && !IsNil(o.Participants) {
		return true
	}

	return false
}

// SetParticipants gets a reference to the given []GetActivitiesResponseAllOfDataInnerParticipantsInner and assigns it to the Participants field.
func (o *AddActivityRequest) SetParticipants(v []GetActivitiesResponseAllOfDataInnerParticipantsInner) {
	o.Participants = v
}

// GetAttendees returns the Attendees field value if set, zero value otherwise.
func (o *AddActivityRequest) GetAttendees() []GetActivitiesResponseAllOfDataInnerAttendeesInner {
	if o == nil || IsNil(o.Attendees) {
		var ret []GetActivitiesResponseAllOfDataInnerAttendeesInner
		return ret
	}
	return o.Attendees
}

// GetAttendeesOk returns a tuple with the Attendees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetAttendeesOk() ([]GetActivitiesResponseAllOfDataInnerAttendeesInner, bool) {
	if o == nil || IsNil(o.Attendees) {
		return nil, false
	}
	return o.Attendees, true
}

// HasAttendees returns a boolean if a field has been set.
func (o *AddActivityRequest) HasAttendees() bool {
	if o != nil && !IsNil(o.Attendees) {
		return true
	}

	return false
}

// SetAttendees gets a reference to the given []GetActivitiesResponseAllOfDataInnerAttendeesInner and assigns it to the Attendees field.
func (o *AddActivityRequest) SetAttendees(v []GetActivitiesResponseAllOfDataInnerAttendeesInner) {
	o.Attendees = v
}

// GetPublicDescription returns the PublicDescription field value if set, zero value otherwise.
func (o *AddActivityRequest) GetPublicDescription() string {
	if o == nil || IsNil(o.PublicDescription) {
		var ret string
		return ret
	}
	return *o.PublicDescription
}

// GetPublicDescriptionOk returns a tuple with the PublicDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetPublicDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.PublicDescription) {
		return nil, false
	}
	return o.PublicDescription, true
}

// HasPublicDescription returns a boolean if a field has been set.
func (o *AddActivityRequest) HasPublicDescription() bool {
	if o != nil && !IsNil(o.PublicDescription) {
		return true
	}

	return false
}

// SetPublicDescription gets a reference to the given string and assigns it to the PublicDescription field.
func (o *AddActivityRequest) SetPublicDescription(v string) {
	o.PublicDescription = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *AddActivityRequest) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *AddActivityRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *AddActivityRequest) SetPriority(v int32) {
	o.Priority = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *AddActivityRequest) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddActivityRequest) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *AddActivityRequest) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *AddActivityRequest) SetNote(v string) {
	o.Note = &v
}

func (o AddActivityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddActivityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.DealId) {
		toSerialize["deal_id"] = o.DealId
	}
	if !IsNil(o.LeadId) {
		toSerialize["lead_id"] = o.LeadId
	}
	if !IsNil(o.PersonId) {
		toSerialize["person_id"] = o.PersonId
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.DueDate) {
		toSerialize["due_date"] = o.DueDate
	}
	if !IsNil(o.DueTime) {
		toSerialize["due_time"] = o.DueTime
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Busy) {
		toSerialize["busy"] = o.Busy
	}
	if !IsNil(o.Done) {
		toSerialize["done"] = o.Done
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Participants) {
		toSerialize["participants"] = o.Participants
	}
	if !IsNil(o.Attendees) {
		toSerialize["attendees"] = o.Attendees
	}
	if !IsNil(o.PublicDescription) {
		toSerialize["public_description"] = o.PublicDescription
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddActivityRequest) UnmarshalJSON(data []byte) (err error) {
	varAddActivityRequest := _AddActivityRequest{}

	err = json.Unmarshal(data, &varAddActivityRequest)

	if err != nil {
		return err
	}

	*o = AddActivityRequest(varAddActivityRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subject")
		delete(additionalProperties, "type")
		delete(additionalProperties, "owner_id")
		delete(additionalProperties, "deal_id")
		delete(additionalProperties, "lead_id")
		delete(additionalProperties, "person_id")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "due_date")
		delete(additionalProperties, "due_time")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "busy")
		delete(additionalProperties, "done")
		delete(additionalProperties, "location")
		delete(additionalProperties, "participants")
		delete(additionalProperties, "attendees")
		delete(additionalProperties, "public_description")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "note")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddActivityRequest struct {
	value *AddActivityRequest
	isSet bool
}

func (v NullableAddActivityRequest) Get() *AddActivityRequest {
	return v.value
}

func (v *NullableAddActivityRequest) Set(val *AddActivityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddActivityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddActivityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddActivityRequest(val *AddActivityRequest) *NullableAddActivityRequest {
	return &NullableAddActivityRequest{value: val, isSet: true}
}

func (v NullableAddActivityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddActivityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


