/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the LeadSearchItemItemOwner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeadSearchItemItemOwner{}

// LeadSearchItemItemOwner struct for LeadSearchItemItemOwner
type LeadSearchItemItemOwner struct {
	// The ID of the owner of the lead
	Id                   *int32 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LeadSearchItemItemOwner LeadSearchItemItemOwner

// NewLeadSearchItemItemOwner instantiates a new LeadSearchItemItemOwner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeadSearchItemItemOwner() *LeadSearchItemItemOwner {
	this := LeadSearchItemItemOwner{}
	return &this
}

// NewLeadSearchItemItemOwnerWithDefaults instantiates a new LeadSearchItemItemOwner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeadSearchItemItemOwnerWithDefaults() *LeadSearchItemItemOwner {
	this := LeadSearchItemItemOwner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LeadSearchItemItemOwner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadSearchItemItemOwner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LeadSearchItemItemOwner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *LeadSearchItemItemOwner) SetId(v int32) {
	o.Id = &v
}

func (o LeadSearchItemItemOwner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeadSearchItemItemOwner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LeadSearchItemItemOwner) UnmarshalJSON(data []byte) (err error) {
	varLeadSearchItemItemOwner := _LeadSearchItemItemOwner{}

	err = json.Unmarshal(data, &varLeadSearchItemItemOwner)

	if err != nil {
		return err
	}

	*o = LeadSearchItemItemOwner(varLeadSearchItemItemOwner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLeadSearchItemItemOwner struct {
	value *LeadSearchItemItemOwner
	isSet bool
}

func (v NullableLeadSearchItemItemOwner) Get() *LeadSearchItemItemOwner {
	return v.value
}

func (v *NullableLeadSearchItemItemOwner) Set(val *LeadSearchItemItemOwner) {
	v.value = val
	v.isSet = true
}

func (v NullableLeadSearchItemItemOwner) IsSet() bool {
	return v.isSet
}

func (v *NullableLeadSearchItemItemOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeadSearchItemItemOwner(val *LeadSearchItemItemOwner) *NullableLeadSearchItemItemOwner {
	return &NullableLeadSearchItemItemOwner{value: val, isSet: true}
}

func (v NullableLeadSearchItemItemOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeadSearchItemItemOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
