/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the ProjectTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectTemplate{}

// ProjectTemplate struct for ProjectTemplate
type ProjectTemplate struct {
	// The ID of the project template
	Id *int32 `json:"id,omitempty"`
	// The title of the project template
	Title *string `json:"title,omitempty"`
	// The description of the project template
	Description *string `json:"description,omitempty"`
	// The ID of the project board this template is associated with
	ProjectsBoardId *int32 `json:"projects_board_id,omitempty"`
	// The ID of the owner of the project template
	OwnerId *int32 `json:"owner_id,omitempty"`
	// The creation date and time of the project template in ISO 8601 format
	AddTime *string `json:"add_time,omitempty"`
	// The update date and time of the project template in ISO 8601 format
	UpdateTime           *string `json:"update_time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProjectTemplate ProjectTemplate

// NewProjectTemplate instantiates a new ProjectTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectTemplate() *ProjectTemplate {
	this := ProjectTemplate{}
	return &this
}

// NewProjectTemplateWithDefaults instantiates a new ProjectTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectTemplateWithDefaults() *ProjectTemplate {
	this := ProjectTemplate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectTemplate) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectTemplate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProjectTemplate) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ProjectTemplate) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ProjectTemplate) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ProjectTemplate) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProjectTemplate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectTemplate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProjectTemplate) SetDescription(v string) {
	o.Description = &v
}

// GetProjectsBoardId returns the ProjectsBoardId field value if set, zero value otherwise.
func (o *ProjectTemplate) GetProjectsBoardId() int32 {
	if o == nil || IsNil(o.ProjectsBoardId) {
		var ret int32
		return ret
	}
	return *o.ProjectsBoardId
}

// GetProjectsBoardIdOk returns a tuple with the ProjectsBoardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetProjectsBoardIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectsBoardId) {
		return nil, false
	}
	return o.ProjectsBoardId, true
}

// HasProjectsBoardId returns a boolean if a field has been set.
func (o *ProjectTemplate) HasProjectsBoardId() bool {
	if o != nil && !IsNil(o.ProjectsBoardId) {
		return true
	}

	return false
}

// SetProjectsBoardId gets a reference to the given int32 and assigns it to the ProjectsBoardId field.
func (o *ProjectTemplate) SetProjectsBoardId(v int32) {
	o.ProjectsBoardId = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *ProjectTemplate) GetOwnerId() int32 {
	if o == nil || IsNil(o.OwnerId) {
		var ret int32
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetOwnerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *ProjectTemplate) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given int32 and assigns it to the OwnerId field.
func (o *ProjectTemplate) SetOwnerId(v int32) {
	o.OwnerId = &v
}

// GetAddTime returns the AddTime field value if set, zero value otherwise.
func (o *ProjectTemplate) GetAddTime() string {
	if o == nil || IsNil(o.AddTime) {
		var ret string
		return ret
	}
	return *o.AddTime
}

// GetAddTimeOk returns a tuple with the AddTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetAddTimeOk() (*string, bool) {
	if o == nil || IsNil(o.AddTime) {
		return nil, false
	}
	return o.AddTime, true
}

// HasAddTime returns a boolean if a field has been set.
func (o *ProjectTemplate) HasAddTime() bool {
	if o != nil && !IsNil(o.AddTime) {
		return true
	}

	return false
}

// SetAddTime gets a reference to the given string and assigns it to the AddTime field.
func (o *ProjectTemplate) SetAddTime(v string) {
	o.AddTime = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *ProjectTemplate) GetUpdateTime() string {
	if o == nil || IsNil(o.UpdateTime) {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTemplate) GetUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *ProjectTemplate) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *ProjectTemplate) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

func (o ProjectTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ProjectsBoardId) {
		toSerialize["projects_board_id"] = o.ProjectsBoardId
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.AddTime) {
		toSerialize["add_time"] = o.AddTime
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["update_time"] = o.UpdateTime
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProjectTemplate) UnmarshalJSON(data []byte) (err error) {
	varProjectTemplate := _ProjectTemplate{}

	err = json.Unmarshal(data, &varProjectTemplate)

	if err != nil {
		return err
	}

	*o = ProjectTemplate(varProjectTemplate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "projects_board_id")
		delete(additionalProperties, "owner_id")
		delete(additionalProperties, "add_time")
		delete(additionalProperties, "update_time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProjectTemplate struct {
	value *ProjectTemplate
	isSet bool
}

func (v NullableProjectTemplate) Get() *ProjectTemplate {
	return v.value
}

func (v *NullableProjectTemplate) Set(val *ProjectTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectTemplate(val *ProjectTemplate) *NullableProjectTemplate {
	return &NullableProjectTemplate{value: val, isSet: true}
}

func (v NullableProjectTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
