/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the Project type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Project{}

// Project struct for Project
type Project struct {
	// The ID of the project
	Id *int32 `json:"id,omitempty"`
	// The title of the project
	Title *string `json:"title,omitempty"`
	// The description of the project
	Description *string `json:"description,omitempty"`
	// The status of the project
	Status *string `json:"status,omitempty"`
	// The ID of the board this project is associated with
	BoardId *int32 `json:"board_id,omitempty"`
	// The ID of the phase this project is associated with
	PhaseId *int32 `json:"phase_id,omitempty"`
	// The ID of the user who owns the project
	OwnerId *int32 `json:"owner_id,omitempty"`
	// The start date of the project. Format: YYYY-MM-DD
	StartDate *string `json:"start_date,omitempty"`
	// The end date of the project. Format: YYYY-MM-DD
	EndDate *string `json:"end_date,omitempty"`
	// An array of IDs of the deals this project is associated with
	DealIds []int32 `json:"deal_ids,omitempty"`
	// An array of IDs of the persons this project is associated with
	PersonIds []int32 `json:"person_ids,omitempty"`
	// An array of IDs of the organizations this project is associated with
	OrgIds []int32 `json:"org_ids,omitempty"`
	// An array of IDs of the labels this project has
	LabelIds []int32 `json:"label_ids,omitempty"`
	// The health status of the project
	HealthStatus NullableInt32 `json:"health_status,omitempty"`
	// The creation date and time of the project in ISO 8601 format
	AddTime *string `json:"add_time,omitempty"`
	// The last updated date and time of the project in ISO 8601 format
	UpdateTime *string `json:"update_time,omitempty"`
	// The date and time of the last status change of the project in ISO 8601 format
	StatusChangeTime *string `json:"status_change_time,omitempty"`
	// The date and time the project was archived in ISO 8601 format. If not archived, this field is null.
	ArchiveTime NullableString `json:"archive_time,omitempty"`
	// An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes. To clear a custom field value, set it to `null`. For multi-option fields (field type `set`), use `null` to clear the selection — sending an empty array `[]` is not supported and will result in a validation error.
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Project Project

// NewProject instantiates a new Project object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProject() *Project {
	this := Project{}
	return &this
}

// NewProjectWithDefaults instantiates a new Project object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectWithDefaults() *Project {
	this := Project{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Project) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Project) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Project) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Project) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Project) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Project) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Project) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Project) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Project) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Project) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Project) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Project) SetStatus(v string) {
	o.Status = &v
}

// GetBoardId returns the BoardId field value if set, zero value otherwise.
func (o *Project) GetBoardId() int32 {
	if o == nil || IsNil(o.BoardId) {
		var ret int32
		return ret
	}
	return *o.BoardId
}

// GetBoardIdOk returns a tuple with the BoardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetBoardIdOk() (*int32, bool) {
	if o == nil || IsNil(o.BoardId) {
		return nil, false
	}
	return o.BoardId, true
}

// HasBoardId returns a boolean if a field has been set.
func (o *Project) HasBoardId() bool {
	if o != nil && !IsNil(o.BoardId) {
		return true
	}

	return false
}

// SetBoardId gets a reference to the given int32 and assigns it to the BoardId field.
func (o *Project) SetBoardId(v int32) {
	o.BoardId = &v
}

// GetPhaseId returns the PhaseId field value if set, zero value otherwise.
func (o *Project) GetPhaseId() int32 {
	if o == nil || IsNil(o.PhaseId) {
		var ret int32
		return ret
	}
	return *o.PhaseId
}

// GetPhaseIdOk returns a tuple with the PhaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetPhaseIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PhaseId) {
		return nil, false
	}
	return o.PhaseId, true
}

// HasPhaseId returns a boolean if a field has been set.
func (o *Project) HasPhaseId() bool {
	if o != nil && !IsNil(o.PhaseId) {
		return true
	}

	return false
}

// SetPhaseId gets a reference to the given int32 and assigns it to the PhaseId field.
func (o *Project) SetPhaseId(v int32) {
	o.PhaseId = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *Project) GetOwnerId() int32 {
	if o == nil || IsNil(o.OwnerId) {
		var ret int32
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetOwnerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *Project) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given int32 and assigns it to the OwnerId field.
func (o *Project) SetOwnerId(v int32) {
	o.OwnerId = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *Project) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *Project) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *Project) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *Project) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *Project) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *Project) SetEndDate(v string) {
	o.EndDate = &v
}

// GetDealIds returns the DealIds field value if set, zero value otherwise.
func (o *Project) GetDealIds() []int32 {
	if o == nil || IsNil(o.DealIds) {
		var ret []int32
		return ret
	}
	return o.DealIds
}

// GetDealIdsOk returns a tuple with the DealIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetDealIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.DealIds) {
		return nil, false
	}
	return o.DealIds, true
}

// HasDealIds returns a boolean if a field has been set.
func (o *Project) HasDealIds() bool {
	if o != nil && !IsNil(o.DealIds) {
		return true
	}

	return false
}

// SetDealIds gets a reference to the given []int32 and assigns it to the DealIds field.
func (o *Project) SetDealIds(v []int32) {
	o.DealIds = v
}

// GetPersonIds returns the PersonIds field value if set, zero value otherwise.
func (o *Project) GetPersonIds() []int32 {
	if o == nil || IsNil(o.PersonIds) {
		var ret []int32
		return ret
	}
	return o.PersonIds
}

// GetPersonIdsOk returns a tuple with the PersonIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetPersonIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.PersonIds) {
		return nil, false
	}
	return o.PersonIds, true
}

// HasPersonIds returns a boolean if a field has been set.
func (o *Project) HasPersonIds() bool {
	if o != nil && !IsNil(o.PersonIds) {
		return true
	}

	return false
}

// SetPersonIds gets a reference to the given []int32 and assigns it to the PersonIds field.
func (o *Project) SetPersonIds(v []int32) {
	o.PersonIds = v
}

// GetOrgIds returns the OrgIds field value if set, zero value otherwise.
func (o *Project) GetOrgIds() []int32 {
	if o == nil || IsNil(o.OrgIds) {
		var ret []int32
		return ret
	}
	return o.OrgIds
}

// GetOrgIdsOk returns a tuple with the OrgIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetOrgIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.OrgIds) {
		return nil, false
	}
	return o.OrgIds, true
}

// HasOrgIds returns a boolean if a field has been set.
func (o *Project) HasOrgIds() bool {
	if o != nil && !IsNil(o.OrgIds) {
		return true
	}

	return false
}

// SetOrgIds gets a reference to the given []int32 and assigns it to the OrgIds field.
func (o *Project) SetOrgIds(v []int32) {
	o.OrgIds = v
}

// GetLabelIds returns the LabelIds field value if set, zero value otherwise.
func (o *Project) GetLabelIds() []int32 {
	if o == nil || IsNil(o.LabelIds) {
		var ret []int32
		return ret
	}
	return o.LabelIds
}

// GetLabelIdsOk returns a tuple with the LabelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetLabelIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.LabelIds) {
		return nil, false
	}
	return o.LabelIds, true
}

// HasLabelIds returns a boolean if a field has been set.
func (o *Project) HasLabelIds() bool {
	if o != nil && !IsNil(o.LabelIds) {
		return true
	}

	return false
}

// SetLabelIds gets a reference to the given []int32 and assigns it to the LabelIds field.
func (o *Project) SetLabelIds(v []int32) {
	o.LabelIds = v
}

// GetHealthStatus returns the HealthStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Project) GetHealthStatus() int32 {
	if o == nil || IsNil(o.HealthStatus.Get()) {
		var ret int32
		return ret
	}
	return *o.HealthStatus.Get()
}

// GetHealthStatusOk returns a tuple with the HealthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Project) GetHealthStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HealthStatus.Get(), o.HealthStatus.IsSet()
}

// HasHealthStatus returns a boolean if a field has been set.
func (o *Project) HasHealthStatus() bool {
	if o != nil && o.HealthStatus.IsSet() {
		return true
	}

	return false
}

// SetHealthStatus gets a reference to the given NullableInt32 and assigns it to the HealthStatus field.
func (o *Project) SetHealthStatus(v int32) {
	o.HealthStatus.Set(&v)
}
// SetHealthStatusNil sets the value for HealthStatus to be an explicit nil
func (o *Project) SetHealthStatusNil() {
	o.HealthStatus.Set(nil)
}

// UnsetHealthStatus ensures that no value is present for HealthStatus, not even an explicit nil
func (o *Project) UnsetHealthStatus() {
	o.HealthStatus.Unset()
}

// GetAddTime returns the AddTime field value if set, zero value otherwise.
func (o *Project) GetAddTime() string {
	if o == nil || IsNil(o.AddTime) {
		var ret string
		return ret
	}
	return *o.AddTime
}

// GetAddTimeOk returns a tuple with the AddTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetAddTimeOk() (*string, bool) {
	if o == nil || IsNil(o.AddTime) {
		return nil, false
	}
	return o.AddTime, true
}

// HasAddTime returns a boolean if a field has been set.
func (o *Project) HasAddTime() bool {
	if o != nil && !IsNil(o.AddTime) {
		return true
	}

	return false
}

// SetAddTime gets a reference to the given string and assigns it to the AddTime field.
func (o *Project) SetAddTime(v string) {
	o.AddTime = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *Project) GetUpdateTime() string {
	if o == nil || IsNil(o.UpdateTime) {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *Project) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *Project) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

// GetStatusChangeTime returns the StatusChangeTime field value if set, zero value otherwise.
func (o *Project) GetStatusChangeTime() string {
	if o == nil || IsNil(o.StatusChangeTime) {
		var ret string
		return ret
	}
	return *o.StatusChangeTime
}

// GetStatusChangeTimeOk returns a tuple with the StatusChangeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetStatusChangeTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StatusChangeTime) {
		return nil, false
	}
	return o.StatusChangeTime, true
}

// HasStatusChangeTime returns a boolean if a field has been set.
func (o *Project) HasStatusChangeTime() bool {
	if o != nil && !IsNil(o.StatusChangeTime) {
		return true
	}

	return false
}

// SetStatusChangeTime gets a reference to the given string and assigns it to the StatusChangeTime field.
func (o *Project) SetStatusChangeTime(v string) {
	o.StatusChangeTime = &v
}

// GetArchiveTime returns the ArchiveTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Project) GetArchiveTime() string {
	if o == nil || IsNil(o.ArchiveTime.Get()) {
		var ret string
		return ret
	}
	return *o.ArchiveTime.Get()
}

// GetArchiveTimeOk returns a tuple with the ArchiveTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Project) GetArchiveTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchiveTime.Get(), o.ArchiveTime.IsSet()
}

// HasArchiveTime returns a boolean if a field has been set.
func (o *Project) HasArchiveTime() bool {
	if o != nil && o.ArchiveTime.IsSet() {
		return true
	}

	return false
}

// SetArchiveTime gets a reference to the given NullableString and assigns it to the ArchiveTime field.
func (o *Project) SetArchiveTime(v string) {
	o.ArchiveTime.Set(&v)
}
// SetArchiveTimeNil sets the value for ArchiveTime to be an explicit nil
func (o *Project) SetArchiveTimeNil() {
	o.ArchiveTime.Set(nil)
}

// UnsetArchiveTime ensures that no value is present for ArchiveTime, not even an explicit nil
func (o *Project) UnsetArchiveTime() {
	o.ArchiveTime.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *Project) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *Project) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *Project) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o Project) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Project) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.BoardId) {
		toSerialize["board_id"] = o.BoardId
	}
	if !IsNil(o.PhaseId) {
		toSerialize["phase_id"] = o.PhaseId
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.DealIds) {
		toSerialize["deal_ids"] = o.DealIds
	}
	if !IsNil(o.PersonIds) {
		toSerialize["person_ids"] = o.PersonIds
	}
	if !IsNil(o.OrgIds) {
		toSerialize["org_ids"] = o.OrgIds
	}
	if !IsNil(o.LabelIds) {
		toSerialize["label_ids"] = o.LabelIds
	}
	if o.HealthStatus.IsSet() {
		toSerialize["health_status"] = o.HealthStatus.Get()
	}
	if !IsNil(o.AddTime) {
		toSerialize["add_time"] = o.AddTime
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["update_time"] = o.UpdateTime
	}
	if !IsNil(o.StatusChangeTime) {
		toSerialize["status_change_time"] = o.StatusChangeTime
	}
	if o.ArchiveTime.IsSet() {
		toSerialize["archive_time"] = o.ArchiveTime.Get()
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Project) UnmarshalJSON(data []byte) (err error) {
	varProject := _Project{}

	err = json.Unmarshal(data, &varProject)

	if err != nil {
		return err
	}

	*o = Project(varProject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "status")
		delete(additionalProperties, "board_id")
		delete(additionalProperties, "phase_id")
		delete(additionalProperties, "owner_id")
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "end_date")
		delete(additionalProperties, "deal_ids")
		delete(additionalProperties, "person_ids")
		delete(additionalProperties, "org_ids")
		delete(additionalProperties, "label_ids")
		delete(additionalProperties, "health_status")
		delete(additionalProperties, "add_time")
		delete(additionalProperties, "update_time")
		delete(additionalProperties, "status_change_time")
		delete(additionalProperties, "archive_time")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProject struct {
	value *Project
	isSet bool
}

func (v NullableProject) Get() *Project {
	return v.value
}

func (v *NullableProject) Set(val *Project) {
	v.value = val
	v.isSet = true
}

func (v NullableProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProject(val *Project) *NullableProject {
	return &NullableProject{value: val, isSet: true}
}

func (v NullableProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


