/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetTasksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTasksResponse{}

// GetTasksResponse struct for GetTasksResponse
type GetTasksResponse struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	Data []GetTasksResponseDataInner `json:"data,omitempty"`
	AdditionalData *GetActivitiesResponseAllOfAdditionalData `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetTasksResponse GetTasksResponse

// NewGetTasksResponse instantiates a new GetTasksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTasksResponse() *GetTasksResponse {
	this := GetTasksResponse{}
	return &this
}

// NewGetTasksResponseWithDefaults instantiates a new GetTasksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTasksResponseWithDefaults() *GetTasksResponse {
	this := GetTasksResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetTasksResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTasksResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetTasksResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetTasksResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetTasksResponse) GetData() []GetTasksResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetTasksResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTasksResponse) GetDataOk() ([]GetTasksResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetTasksResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetTasksResponseDataInner and assigns it to the Data field.
func (o *GetTasksResponse) SetData(v []GetTasksResponseDataInner) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetTasksResponse) GetAdditionalData() GetActivitiesResponseAllOfAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetActivitiesResponseAllOfAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTasksResponse) GetAdditionalDataOk() (*GetActivitiesResponseAllOfAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetTasksResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetActivitiesResponseAllOfAdditionalData and assigns it to the AdditionalData field.
func (o *GetTasksResponse) SetAdditionalData(v GetActivitiesResponseAllOfAdditionalData) {
	o.AdditionalData = &v
}

func (o GetTasksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTasksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetTasksResponse) UnmarshalJSON(data []byte) (err error) {
	varGetTasksResponse := _GetTasksResponse{}

	err = json.Unmarshal(data, &varGetTasksResponse)

	if err != nil {
		return err
	}

	*o = GetTasksResponse(varGetTasksResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetTasksResponse struct {
	value *GetTasksResponse
	isSet bool
}

func (v NullableGetTasksResponse) Get() *GetTasksResponse {
	return v.value
}

func (v *NullableGetTasksResponse) Set(val *GetTasksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTasksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTasksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTasksResponse(val *GetTasksResponse) *NullableGetTasksResponse {
	return &NullableGetTasksResponse{value: val, isSet: true}
}

func (v NullableGetTasksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTasksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


