/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the AddPersonFieldRequestRequiredFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddPersonFieldRequestRequiredFields{}

// AddPersonFieldRequestRequiredFields Required fields configuration for marking the field as mandatory when interacted with in the Pipedrive web UI.
type AddPersonFieldRequestRequiredFields struct {
	// Whether the field is required. When false, the field is optional. When true, the field is required when creating or updating persons. Default is false.
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddPersonFieldRequestRequiredFields AddPersonFieldRequestRequiredFields

// NewAddPersonFieldRequestRequiredFields instantiates a new AddPersonFieldRequestRequiredFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPersonFieldRequestRequiredFields() *AddPersonFieldRequestRequiredFields {
	this := AddPersonFieldRequestRequiredFields{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewAddPersonFieldRequestRequiredFieldsWithDefaults instantiates a new AddPersonFieldRequestRequiredFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPersonFieldRequestRequiredFieldsWithDefaults() *AddPersonFieldRequestRequiredFields {
	this := AddPersonFieldRequestRequiredFields{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AddPersonFieldRequestRequiredFields) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPersonFieldRequestRequiredFields) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AddPersonFieldRequestRequiredFields) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AddPersonFieldRequestRequiredFields) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o AddPersonFieldRequestRequiredFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddPersonFieldRequestRequiredFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddPersonFieldRequestRequiredFields) UnmarshalJSON(data []byte) (err error) {
	varAddPersonFieldRequestRequiredFields := _AddPersonFieldRequestRequiredFields{}

	err = json.Unmarshal(data, &varAddPersonFieldRequestRequiredFields)

	if err != nil {
		return err
	}

	*o = AddPersonFieldRequestRequiredFields(varAddPersonFieldRequestRequiredFields)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddPersonFieldRequestRequiredFields struct {
	value *AddPersonFieldRequestRequiredFields
	isSet bool
}

func (v NullableAddPersonFieldRequestRequiredFields) Get() *AddPersonFieldRequestRequiredFields {
	return v.value
}

func (v *NullableAddPersonFieldRequestRequiredFields) Set(val *AddPersonFieldRequestRequiredFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPersonFieldRequestRequiredFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPersonFieldRequestRequiredFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPersonFieldRequestRequiredFields(val *AddPersonFieldRequestRequiredFields) *NullableAddPersonFieldRequestRequiredFields {
	return &NullableAddPersonFieldRequestRequiredFields{value: val, isSet: true}
}

func (v NullableAddPersonFieldRequestRequiredFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddPersonFieldRequestRequiredFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


