/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetPersonsResponseAllOfDataInnerPhonesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPersonsResponseAllOfDataInnerPhonesInner{}

// GetPersonsResponseAllOfDataInnerPhonesInner struct for GetPersonsResponseAllOfDataInnerPhonesInner
type GetPersonsResponseAllOfDataInnerPhonesInner struct {
	// The phone number of the person
	Value *string `json:"value,omitempty"`
	// Whether the phone number is primary or not
	Primary *bool `json:"primary,omitempty"`
	// The phone number classification label
	Label *string `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetPersonsResponseAllOfDataInnerPhonesInner GetPersonsResponseAllOfDataInnerPhonesInner

// NewGetPersonsResponseAllOfDataInnerPhonesInner instantiates a new GetPersonsResponseAllOfDataInnerPhonesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPersonsResponseAllOfDataInnerPhonesInner() *GetPersonsResponseAllOfDataInnerPhonesInner {
	this := GetPersonsResponseAllOfDataInnerPhonesInner{}
	return &this
}

// NewGetPersonsResponseAllOfDataInnerPhonesInnerWithDefaults instantiates a new GetPersonsResponseAllOfDataInnerPhonesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPersonsResponseAllOfDataInnerPhonesInnerWithDefaults() *GetPersonsResponseAllOfDataInnerPhonesInner {
	this := GetPersonsResponseAllOfDataInnerPhonesInner{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) SetValue(v string) {
	o.Value = &v
}

// GetPrimary returns the Primary field value if set, zero value otherwise.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) GetPrimary() bool {
	if o == nil || IsNil(o.Primary) {
		var ret bool
		return ret
	}
	return *o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) GetPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.Primary) {
		return nil, false
	}
	return o.Primary, true
}

// HasPrimary returns a boolean if a field has been set.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) HasPrimary() bool {
	if o != nil && !IsNil(o.Primary) {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given bool and assigns it to the Primary field.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) SetPrimary(v bool) {
	o.Primary = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GetPersonsResponseAllOfDataInnerPhonesInner) SetLabel(v string) {
	o.Label = &v
}

func (o GetPersonsResponseAllOfDataInnerPhonesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPersonsResponseAllOfDataInnerPhonesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Primary) {
		toSerialize["primary"] = o.Primary
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPersonsResponseAllOfDataInnerPhonesInner) UnmarshalJSON(data []byte) (err error) {
	varGetPersonsResponseAllOfDataInnerPhonesInner := _GetPersonsResponseAllOfDataInnerPhonesInner{}

	err = json.Unmarshal(data, &varGetPersonsResponseAllOfDataInnerPhonesInner)

	if err != nil {
		return err
	}

	*o = GetPersonsResponseAllOfDataInnerPhonesInner(varGetPersonsResponseAllOfDataInnerPhonesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "primary")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPersonsResponseAllOfDataInnerPhonesInner struct {
	value *GetPersonsResponseAllOfDataInnerPhonesInner
	isSet bool
}

func (v NullableGetPersonsResponseAllOfDataInnerPhonesInner) Get() *GetPersonsResponseAllOfDataInnerPhonesInner {
	return v.value
}

func (v *NullableGetPersonsResponseAllOfDataInnerPhonesInner) Set(val *GetPersonsResponseAllOfDataInnerPhonesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPersonsResponseAllOfDataInnerPhonesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPersonsResponseAllOfDataInnerPhonesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPersonsResponseAllOfDataInnerPhonesInner(val *GetPersonsResponseAllOfDataInnerPhonesInner) *NullableGetPersonsResponseAllOfDataInnerPhonesInner {
	return &NullableGetPersonsResponseAllOfDataInnerPhonesInner{value: val, isSet: true}
}

func (v NullableGetPersonsResponseAllOfDataInnerPhonesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPersonsResponseAllOfDataInnerPhonesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


