/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetPersonsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPersonsResponse{}

// GetPersonsResponse struct for GetPersonsResponse
type GetPersonsResponse struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	// Persons array
	Data []GetPersonsResponseAllOfDataInner `json:"data,omitempty"`
	AdditionalData *GetActivitiesResponseAllOfAdditionalData `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetPersonsResponse GetPersonsResponse

// NewGetPersonsResponse instantiates a new GetPersonsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPersonsResponse() *GetPersonsResponse {
	this := GetPersonsResponse{}
	return &this
}

// NewGetPersonsResponseWithDefaults instantiates a new GetPersonsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPersonsResponseWithDefaults() *GetPersonsResponse {
	this := GetPersonsResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetPersonsResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetPersonsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetPersonsResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPersonsResponse) GetData() []GetPersonsResponseAllOfDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetPersonsResponseAllOfDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonsResponse) GetDataOk() ([]GetPersonsResponseAllOfDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPersonsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetPersonsResponseAllOfDataInner and assigns it to the Data field.
func (o *GetPersonsResponse) SetData(v []GetPersonsResponseAllOfDataInner) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetPersonsResponse) GetAdditionalData() GetActivitiesResponseAllOfAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetActivitiesResponseAllOfAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonsResponse) GetAdditionalDataOk() (*GetActivitiesResponseAllOfAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetPersonsResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetActivitiesResponseAllOfAdditionalData and assigns it to the AdditionalData field.
func (o *GetPersonsResponse) SetAdditionalData(v GetActivitiesResponseAllOfAdditionalData) {
	o.AdditionalData = &v
}

func (o GetPersonsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPersonsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPersonsResponse) UnmarshalJSON(data []byte) (err error) {
	varGetPersonsResponse := _GetPersonsResponse{}

	err = json.Unmarshal(data, &varGetPersonsResponse)

	if err != nil {
		return err
	}

	*o = GetPersonsResponse(varGetPersonsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPersonsResponse struct {
	value *GetPersonsResponse
	isSet bool
}

func (v NullableGetPersonsResponse) Get() *GetPersonsResponse {
	return v.value
}

func (v *NullableGetPersonsResponse) Set(val *GetPersonsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPersonsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPersonsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPersonsResponse(val *GetPersonsResponse) *NullableGetPersonsResponse {
	return &NullableGetPersonsResponse{value: val, isSet: true}
}

func (v NullableGetPersonsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPersonsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


