/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the FollowerChangelogItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FollowerChangelogItem{}

// FollowerChangelogItem struct for FollowerChangelogItem
type FollowerChangelogItem struct {
	// The type of change
	Action *string `json:"action,omitempty"`
	// The ID of the user who did the change
	ActorUserId *int32 `json:"actor_user_id,omitempty"`
	// The ID of the user who was following the entity
	FollowerUserId *int32 `json:"follower_user_id,omitempty"`
	// The time at which the change happened
	Time *string `json:"time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FollowerChangelogItem FollowerChangelogItem

// NewFollowerChangelogItem instantiates a new FollowerChangelogItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFollowerChangelogItem() *FollowerChangelogItem {
	this := FollowerChangelogItem{}
	return &this
}

// NewFollowerChangelogItemWithDefaults instantiates a new FollowerChangelogItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFollowerChangelogItemWithDefaults() *FollowerChangelogItem {
	this := FollowerChangelogItem{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *FollowerChangelogItem) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FollowerChangelogItem) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *FollowerChangelogItem) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *FollowerChangelogItem) SetAction(v string) {
	o.Action = &v
}

// GetActorUserId returns the ActorUserId field value if set, zero value otherwise.
func (o *FollowerChangelogItem) GetActorUserId() int32 {
	if o == nil || IsNil(o.ActorUserId) {
		var ret int32
		return ret
	}
	return *o.ActorUserId
}

// GetActorUserIdOk returns a tuple with the ActorUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FollowerChangelogItem) GetActorUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ActorUserId) {
		return nil, false
	}
	return o.ActorUserId, true
}

// HasActorUserId returns a boolean if a field has been set.
func (o *FollowerChangelogItem) HasActorUserId() bool {
	if o != nil && !IsNil(o.ActorUserId) {
		return true
	}

	return false
}

// SetActorUserId gets a reference to the given int32 and assigns it to the ActorUserId field.
func (o *FollowerChangelogItem) SetActorUserId(v int32) {
	o.ActorUserId = &v
}

// GetFollowerUserId returns the FollowerUserId field value if set, zero value otherwise.
func (o *FollowerChangelogItem) GetFollowerUserId() int32 {
	if o == nil || IsNil(o.FollowerUserId) {
		var ret int32
		return ret
	}
	return *o.FollowerUserId
}

// GetFollowerUserIdOk returns a tuple with the FollowerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FollowerChangelogItem) GetFollowerUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FollowerUserId) {
		return nil, false
	}
	return o.FollowerUserId, true
}

// HasFollowerUserId returns a boolean if a field has been set.
func (o *FollowerChangelogItem) HasFollowerUserId() bool {
	if o != nil && !IsNil(o.FollowerUserId) {
		return true
	}

	return false
}

// SetFollowerUserId gets a reference to the given int32 and assigns it to the FollowerUserId field.
func (o *FollowerChangelogItem) SetFollowerUserId(v int32) {
	o.FollowerUserId = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *FollowerChangelogItem) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FollowerChangelogItem) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *FollowerChangelogItem) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *FollowerChangelogItem) SetTime(v string) {
	o.Time = &v
}

func (o FollowerChangelogItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FollowerChangelogItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.ActorUserId) {
		toSerialize["actor_user_id"] = o.ActorUserId
	}
	if !IsNil(o.FollowerUserId) {
		toSerialize["follower_user_id"] = o.FollowerUserId
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FollowerChangelogItem) UnmarshalJSON(data []byte) (err error) {
	varFollowerChangelogItem := _FollowerChangelogItem{}

	err = json.Unmarshal(data, &varFollowerChangelogItem)

	if err != nil {
		return err
	}

	*o = FollowerChangelogItem(varFollowerChangelogItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "actor_user_id")
		delete(additionalProperties, "follower_user_id")
		delete(additionalProperties, "time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFollowerChangelogItem struct {
	value *FollowerChangelogItem
	isSet bool
}

func (v NullableFollowerChangelogItem) Get() *FollowerChangelogItem {
	return v.value
}

func (v *NullableFollowerChangelogItem) Set(val *FollowerChangelogItem) {
	v.value = val
	v.isSet = true
}

func (v NullableFollowerChangelogItem) IsSet() bool {
	return v.isSet
}

func (v *NullableFollowerChangelogItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFollowerChangelogItem(val *FollowerChangelogItem) *NullableFollowerChangelogItem {
	return &NullableFollowerChangelogItem{value: val, isSet: true}
}

func (v NullableFollowerChangelogItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFollowerChangelogItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


