/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the DeleteProjectPhaseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteProjectPhaseResponse{}

// DeleteProjectPhaseResponse struct for DeleteProjectPhaseResponse
type DeleteProjectPhaseResponse struct {
	// If the response is successful or not
	Success              *bool                           `json:"success,omitempty"`
	Data                 *DeleteProjectPhaseResponseData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeleteProjectPhaseResponse DeleteProjectPhaseResponse

// NewDeleteProjectPhaseResponse instantiates a new DeleteProjectPhaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteProjectPhaseResponse() *DeleteProjectPhaseResponse {
	this := DeleteProjectPhaseResponse{}
	return &this
}

// NewDeleteProjectPhaseResponseWithDefaults instantiates a new DeleteProjectPhaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteProjectPhaseResponseWithDefaults() *DeleteProjectPhaseResponse {
	this := DeleteProjectPhaseResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *DeleteProjectPhaseResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteProjectPhaseResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *DeleteProjectPhaseResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *DeleteProjectPhaseResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DeleteProjectPhaseResponse) GetData() DeleteProjectPhaseResponseData {
	if o == nil || IsNil(o.Data) {
		var ret DeleteProjectPhaseResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteProjectPhaseResponse) GetDataOk() (*DeleteProjectPhaseResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DeleteProjectPhaseResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given DeleteProjectPhaseResponseData and assigns it to the Data field.
func (o *DeleteProjectPhaseResponse) SetData(v DeleteProjectPhaseResponseData) {
	o.Data = &v
}

func (o DeleteProjectPhaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteProjectPhaseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteProjectPhaseResponse) UnmarshalJSON(data []byte) (err error) {
	varDeleteProjectPhaseResponse := _DeleteProjectPhaseResponse{}

	err = json.Unmarshal(data, &varDeleteProjectPhaseResponse)

	if err != nil {
		return err
	}

	*o = DeleteProjectPhaseResponse(varDeleteProjectPhaseResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteProjectPhaseResponse struct {
	value *DeleteProjectPhaseResponse
	isSet bool
}

func (v NullableDeleteProjectPhaseResponse) Get() *DeleteProjectPhaseResponse {
	return v.value
}

func (v *NullableDeleteProjectPhaseResponse) Set(val *DeleteProjectPhaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteProjectPhaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteProjectPhaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteProjectPhaseResponse(val *DeleteProjectPhaseResponse) *NullableDeleteProjectPhaseResponse {
	return &NullableDeleteProjectPhaseResponse{value: val, isSet: true}
}

func (v NullableDeleteProjectPhaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteProjectPhaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
