/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the DeletePersonResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePersonResponseData{}

// DeletePersonResponseData struct for DeletePersonResponseData
type DeletePersonResponseData struct {
	// Deleted person ID
	Id                   *int32 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeletePersonResponseData DeletePersonResponseData

// NewDeletePersonResponseData instantiates a new DeletePersonResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePersonResponseData() *DeletePersonResponseData {
	this := DeletePersonResponseData{}
	return &this
}

// NewDeletePersonResponseDataWithDefaults instantiates a new DeletePersonResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePersonResponseDataWithDefaults() *DeletePersonResponseData {
	this := DeletePersonResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeletePersonResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePersonResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeletePersonResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DeletePersonResponseData) SetId(v int32) {
	o.Id = &v
}

func (o DeletePersonResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePersonResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeletePersonResponseData) UnmarshalJSON(data []byte) (err error) {
	varDeletePersonResponseData := _DeletePersonResponseData{}

	err = json.Unmarshal(data, &varDeletePersonResponseData)

	if err != nil {
		return err
	}

	*o = DeletePersonResponseData(varDeletePersonResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeletePersonResponseData struct {
	value *DeletePersonResponseData
	isSet bool
}

func (v NullableDeletePersonResponseData) Get() *DeletePersonResponseData {
	return v.value
}

func (v *NullableDeletePersonResponseData) Set(val *DeletePersonResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePersonResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePersonResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePersonResponseData(val *DeletePersonResponseData) *NullableDeletePersonResponseData {
	return &NullableDeletePersonResponseData{value: val, isSet: true}
}

func (v NullableDeletePersonResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePersonResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
