/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the UpdateProductFieldRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProductFieldRequest{}

// UpdateProductFieldRequest struct for UpdateProductFieldRequest
type UpdateProductFieldRequest struct {
	// Field name
	FieldName            *string                             `json:"field_name,omitempty"`
	UiVisibility         *AddProductFieldRequestUiVisibility `json:"ui_visibility,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateProductFieldRequest UpdateProductFieldRequest

// NewUpdateProductFieldRequest instantiates a new UpdateProductFieldRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProductFieldRequest() *UpdateProductFieldRequest {
	this := UpdateProductFieldRequest{}
	return &this
}

// NewUpdateProductFieldRequestWithDefaults instantiates a new UpdateProductFieldRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProductFieldRequestWithDefaults() *UpdateProductFieldRequest {
	this := UpdateProductFieldRequest{}
	return &this
}

// GetFieldName returns the FieldName field value if set, zero value otherwise.
func (o *UpdateProductFieldRequest) GetFieldName() string {
	if o == nil || IsNil(o.FieldName) {
		var ret string
		return ret
	}
	return *o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProductFieldRequest) GetFieldNameOk() (*string, bool) {
	if o == nil || IsNil(o.FieldName) {
		return nil, false
	}
	return o.FieldName, true
}

// HasFieldName returns a boolean if a field has been set.
func (o *UpdateProductFieldRequest) HasFieldName() bool {
	if o != nil && !IsNil(o.FieldName) {
		return true
	}

	return false
}

// SetFieldName gets a reference to the given string and assigns it to the FieldName field.
func (o *UpdateProductFieldRequest) SetFieldName(v string) {
	o.FieldName = &v
}

// GetUiVisibility returns the UiVisibility field value if set, zero value otherwise.
func (o *UpdateProductFieldRequest) GetUiVisibility() AddProductFieldRequestUiVisibility {
	if o == nil || IsNil(o.UiVisibility) {
		var ret AddProductFieldRequestUiVisibility
		return ret
	}
	return *o.UiVisibility
}

// GetUiVisibilityOk returns a tuple with the UiVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProductFieldRequest) GetUiVisibilityOk() (*AddProductFieldRequestUiVisibility, bool) {
	if o == nil || IsNil(o.UiVisibility) {
		return nil, false
	}
	return o.UiVisibility, true
}

// HasUiVisibility returns a boolean if a field has been set.
func (o *UpdateProductFieldRequest) HasUiVisibility() bool {
	if o != nil && !IsNil(o.UiVisibility) {
		return true
	}

	return false
}

// SetUiVisibility gets a reference to the given AddProductFieldRequestUiVisibility and assigns it to the UiVisibility field.
func (o *UpdateProductFieldRequest) SetUiVisibility(v AddProductFieldRequestUiVisibility) {
	o.UiVisibility = &v
}

func (o UpdateProductFieldRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProductFieldRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldName) {
		toSerialize["field_name"] = o.FieldName
	}
	if !IsNil(o.UiVisibility) {
		toSerialize["ui_visibility"] = o.UiVisibility
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateProductFieldRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateProductFieldRequest := _UpdateProductFieldRequest{}

	err = json.Unmarshal(data, &varUpdateProductFieldRequest)

	if err != nil {
		return err
	}

	*o = UpdateProductFieldRequest(varUpdateProductFieldRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "field_name")
		delete(additionalProperties, "ui_visibility")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateProductFieldRequest struct {
	value *UpdateProductFieldRequest
	isSet bool
}

func (v NullableUpdateProductFieldRequest) Get() *UpdateProductFieldRequest {
	return v.value
}

func (v *NullableUpdateProductFieldRequest) Set(val *UpdateProductFieldRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProductFieldRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProductFieldRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProductFieldRequest(val *UpdateProductFieldRequest) *NullableUpdateProductFieldRequest {
	return &NullableUpdateProductFieldRequest{value: val, isSet: true}
}

func (v NullableUpdateProductFieldRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProductFieldRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
