/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetTaskResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTaskResponse{}

// GetTaskResponse struct for GetTaskResponse
type GetTaskResponse struct {
	// If the response is successful or not
	Success              *bool                      `json:"success,omitempty"`
	Data                 *GetTasksResponseDataInner `json:"data,omitempty"`
	AdditionalData       map[string]interface{}     `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetTaskResponse GetTaskResponse

// NewGetTaskResponse instantiates a new GetTaskResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTaskResponse() *GetTaskResponse {
	this := GetTaskResponse{}
	return &this
}

// NewGetTaskResponseWithDefaults instantiates a new GetTaskResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTaskResponseWithDefaults() *GetTaskResponse {
	this := GetTaskResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetTaskResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTaskResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetTaskResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetTaskResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetTaskResponse) GetData() GetTasksResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret GetTasksResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTaskResponse) GetDataOk() (*GetTasksResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetTaskResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetTasksResponseDataInner and assigns it to the Data field.
func (o *GetTaskResponse) SetData(v GetTasksResponseDataInner) {
	o.Data = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetTaskResponse) GetAdditionalData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetTaskResponse) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetTaskResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *GetTaskResponse) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

func (o GetTaskResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTaskResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.AdditionalData != nil {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetTaskResponse) UnmarshalJSON(data []byte) (err error) {
	varGetTaskResponse := _GetTaskResponse{}

	err = json.Unmarshal(data, &varGetTaskResponse)

	if err != nil {
		return err
	}

	*o = GetTaskResponse(varGetTaskResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetTaskResponse struct {
	value *GetTaskResponse
	isSet bool
}

func (v NullableGetTaskResponse) Get() *GetTaskResponse {
	return v.value
}

func (v *NullableGetTaskResponse) Set(val *GetTaskResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTaskResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTaskResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTaskResponse(val *GetTaskResponse) *NullableGetTaskResponse {
	return &NullableGetTaskResponse{value: val, isSet: true}
}

func (v NullableGetTaskResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTaskResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
