/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the AddAdditionalDiscountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAdditionalDiscountResponse{}

// AddAdditionalDiscountResponse struct for AddAdditionalDiscountResponse
type AddAdditionalDiscountResponse struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	Data *GetAdditionalDiscountsResponseDataInner `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddAdditionalDiscountResponse AddAdditionalDiscountResponse

// NewAddAdditionalDiscountResponse instantiates a new AddAdditionalDiscountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAdditionalDiscountResponse() *AddAdditionalDiscountResponse {
	this := AddAdditionalDiscountResponse{}
	return &this
}

// NewAddAdditionalDiscountResponseWithDefaults instantiates a new AddAdditionalDiscountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAdditionalDiscountResponseWithDefaults() *AddAdditionalDiscountResponse {
	this := AddAdditionalDiscountResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *AddAdditionalDiscountResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAdditionalDiscountResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *AddAdditionalDiscountResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *AddAdditionalDiscountResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AddAdditionalDiscountResponse) GetData() GetAdditionalDiscountsResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret GetAdditionalDiscountsResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAdditionalDiscountResponse) GetDataOk() (*GetAdditionalDiscountsResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AddAdditionalDiscountResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetAdditionalDiscountsResponseDataInner and assigns it to the Data field.
func (o *AddAdditionalDiscountResponse) SetData(v GetAdditionalDiscountsResponseDataInner) {
	o.Data = &v
}

func (o AddAdditionalDiscountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAdditionalDiscountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddAdditionalDiscountResponse) UnmarshalJSON(data []byte) (err error) {
	varAddAdditionalDiscountResponse := _AddAdditionalDiscountResponse{}

	err = json.Unmarshal(data, &varAddAdditionalDiscountResponse)

	if err != nil {
		return err
	}

	*o = AddAdditionalDiscountResponse(varAddAdditionalDiscountResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddAdditionalDiscountResponse struct {
	value *AddAdditionalDiscountResponse
	isSet bool
}

func (v NullableAddAdditionalDiscountResponse) Get() *AddAdditionalDiscountResponse {
	return v.value
}

func (v *NullableAddAdditionalDiscountResponse) Set(val *AddAdditionalDiscountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAdditionalDiscountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAdditionalDiscountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAdditionalDiscountResponse(val *AddAdditionalDiscountResponse) *NullableAddAdditionalDiscountResponse {
	return &NullableAddAdditionalDiscountResponse{value: val, isSet: true}
}

func (v NullableAddAdditionalDiscountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAdditionalDiscountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


