/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetConvertResponse1Data type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConvertResponse1Data{}

// GetConvertResponse1Data An object containing conversion status. After successful conversion the converted entity ID is also present.
type GetConvertResponse1Data struct {
	// The ID of the new lead.
	LeadId *string `json:"lead_id,omitempty"`
	// The ID of the new deal.
	DealId *int32 `json:"deal_id,omitempty"`
	// The ID of the conversion job. The ID can be used to retrieve conversion status and details. The ID has UUID format.
	ConversionId string `json:"conversion_id"`
	// Status of the conversion job.
	Status               string `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _GetConvertResponse1Data GetConvertResponse1Data

// NewGetConvertResponse1Data instantiates a new GetConvertResponse1Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConvertResponse1Data(conversionId string, status string) *GetConvertResponse1Data {
	this := GetConvertResponse1Data{}
	this.ConversionId = conversionId
	this.Status = status
	return &this
}

// NewGetConvertResponse1DataWithDefaults instantiates a new GetConvertResponse1Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConvertResponse1DataWithDefaults() *GetConvertResponse1Data {
	this := GetConvertResponse1Data{}
	return &this
}

// GetLeadId returns the LeadId field value if set, zero value otherwise.
func (o *GetConvertResponse1Data) GetLeadId() string {
	if o == nil || IsNil(o.LeadId) {
		var ret string
		return ret
	}
	return *o.LeadId
}

// GetLeadIdOk returns a tuple with the LeadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConvertResponse1Data) GetLeadIdOk() (*string, bool) {
	if o == nil || IsNil(o.LeadId) {
		return nil, false
	}
	return o.LeadId, true
}

// HasLeadId returns a boolean if a field has been set.
func (o *GetConvertResponse1Data) HasLeadId() bool {
	if o != nil && !IsNil(o.LeadId) {
		return true
	}

	return false
}

// SetLeadId gets a reference to the given string and assigns it to the LeadId field.
func (o *GetConvertResponse1Data) SetLeadId(v string) {
	o.LeadId = &v
}

// GetDealId returns the DealId field value if set, zero value otherwise.
func (o *GetConvertResponse1Data) GetDealId() int32 {
	if o == nil || IsNil(o.DealId) {
		var ret int32
		return ret
	}
	return *o.DealId
}

// GetDealIdOk returns a tuple with the DealId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConvertResponse1Data) GetDealIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DealId) {
		return nil, false
	}
	return o.DealId, true
}

// HasDealId returns a boolean if a field has been set.
func (o *GetConvertResponse1Data) HasDealId() bool {
	if o != nil && !IsNil(o.DealId) {
		return true
	}

	return false
}

// SetDealId gets a reference to the given int32 and assigns it to the DealId field.
func (o *GetConvertResponse1Data) SetDealId(v int32) {
	o.DealId = &v
}

// GetConversionId returns the ConversionId field value
func (o *GetConvertResponse1Data) GetConversionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversionId
}

// GetConversionIdOk returns a tuple with the ConversionId field value
// and a boolean to check if the value has been set.
func (o *GetConvertResponse1Data) GetConversionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversionId, true
}

// SetConversionId sets field value
func (o *GetConvertResponse1Data) SetConversionId(v string) {
	o.ConversionId = v
}

// GetStatus returns the Status field value
func (o *GetConvertResponse1Data) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetConvertResponse1Data) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetConvertResponse1Data) SetStatus(v string) {
	o.Status = v
}

func (o GetConvertResponse1Data) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConvertResponse1Data) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LeadId) {
		toSerialize["lead_id"] = o.LeadId
	}
	if !IsNil(o.DealId) {
		toSerialize["deal_id"] = o.DealId
	}
	toSerialize["conversion_id"] = o.ConversionId
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetConvertResponse1Data) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conversion_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetConvertResponse1Data := _GetConvertResponse1Data{}

	err = json.Unmarshal(data, &varGetConvertResponse1Data)

	if err != nil {
		return err
	}

	*o = GetConvertResponse1Data(varGetConvertResponse1Data)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "lead_id")
		delete(additionalProperties, "deal_id")
		delete(additionalProperties, "conversion_id")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetConvertResponse1Data struct {
	value *GetConvertResponse1Data
	isSet bool
}

func (v NullableGetConvertResponse1Data) Get() *GetConvertResponse1Data {
	return v.value
}

func (v *NullableGetConvertResponse1Data) Set(val *GetConvertResponse1Data) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConvertResponse1Data) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConvertResponse1Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConvertResponse1Data(val *GetConvertResponse1Data) *NullableGetConvertResponse1Data {
	return &NullableGetConvertResponse1Data{value: val, isSet: true}
}

func (v NullableGetConvertResponse1Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConvertResponse1Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
