/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetPipelinesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPipelinesResponse{}

// GetPipelinesResponse struct for GetPipelinesResponse
type GetPipelinesResponse struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	// Pipelines array
	Data []GetPipelinesResponseAllOfDataInner `json:"data,omitempty"`
	AdditionalData *GetActivitiesResponseAllOfAdditionalData `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetPipelinesResponse GetPipelinesResponse

// NewGetPipelinesResponse instantiates a new GetPipelinesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPipelinesResponse() *GetPipelinesResponse {
	this := GetPipelinesResponse{}
	return &this
}

// NewGetPipelinesResponseWithDefaults instantiates a new GetPipelinesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPipelinesResponseWithDefaults() *GetPipelinesResponse {
	this := GetPipelinesResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetPipelinesResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPipelinesResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetPipelinesResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetPipelinesResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPipelinesResponse) GetData() []GetPipelinesResponseAllOfDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetPipelinesResponseAllOfDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPipelinesResponse) GetDataOk() ([]GetPipelinesResponseAllOfDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPipelinesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetPipelinesResponseAllOfDataInner and assigns it to the Data field.
func (o *GetPipelinesResponse) SetData(v []GetPipelinesResponseAllOfDataInner) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetPipelinesResponse) GetAdditionalData() GetActivitiesResponseAllOfAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetActivitiesResponseAllOfAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPipelinesResponse) GetAdditionalDataOk() (*GetActivitiesResponseAllOfAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetPipelinesResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetActivitiesResponseAllOfAdditionalData and assigns it to the AdditionalData field.
func (o *GetPipelinesResponse) SetAdditionalData(v GetActivitiesResponseAllOfAdditionalData) {
	o.AdditionalData = &v
}

func (o GetPipelinesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPipelinesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPipelinesResponse) UnmarshalJSON(data []byte) (err error) {
	varGetPipelinesResponse := _GetPipelinesResponse{}

	err = json.Unmarshal(data, &varGetPipelinesResponse)

	if err != nil {
		return err
	}

	*o = GetPipelinesResponse(varGetPipelinesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPipelinesResponse struct {
	value *GetPipelinesResponse
	isSet bool
}

func (v NullableGetPipelinesResponse) Get() *GetPipelinesResponse {
	return v.value
}

func (v *NullableGetPipelinesResponse) Set(val *GetPipelinesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPipelinesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPipelinesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPipelinesResponse(val *GetPipelinesResponse) *NullableGetPipelinesResponse {
	return &NullableGetPipelinesResponse{value: val, isSet: true}
}

func (v NullableGetPipelinesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPipelinesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


