/*
Pipedrive API v2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the GetProjectTemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectTemplateResponse{}

// GetProjectTemplateResponse struct for GetProjectTemplateResponse
type GetProjectTemplateResponse struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	Data *ProjectTemplate `json:"data,omitempty"`
	AdditionalData map[string]interface{} `json:"additional_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetProjectTemplateResponse GetProjectTemplateResponse

// NewGetProjectTemplateResponse instantiates a new GetProjectTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectTemplateResponse() *GetProjectTemplateResponse {
	this := GetProjectTemplateResponse{}
	return &this
}

// NewGetProjectTemplateResponseWithDefaults instantiates a new GetProjectTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectTemplateResponseWithDefaults() *GetProjectTemplateResponse {
	this := GetProjectTemplateResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetProjectTemplateResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectTemplateResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetProjectTemplateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetProjectTemplateResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetProjectTemplateResponse) GetData() ProjectTemplate {
	if o == nil || IsNil(o.Data) {
		var ret ProjectTemplate
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectTemplateResponse) GetDataOk() (*ProjectTemplate, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetProjectTemplateResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ProjectTemplate and assigns it to the Data field.
func (o *GetProjectTemplateResponse) SetData(v ProjectTemplate) {
	o.Data = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectTemplateResponse) GetAdditionalData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectTemplateResponse) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetProjectTemplateResponse) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *GetProjectTemplateResponse) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

func (o GetProjectTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectTemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.AdditionalData != nil {
		toSerialize["additional_data"] = o.AdditionalData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProjectTemplateResponse) UnmarshalJSON(data []byte) (err error) {
	varGetProjectTemplateResponse := _GetProjectTemplateResponse{}

	err = json.Unmarshal(data, &varGetProjectTemplateResponse)

	if err != nil {
		return err
	}

	*o = GetProjectTemplateResponse(varGetProjectTemplateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		delete(additionalProperties, "additional_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProjectTemplateResponse struct {
	value *GetProjectTemplateResponse
	isSet bool
}

func (v NullableGetProjectTemplateResponse) Get() *GetProjectTemplateResponse {
	return v.value
}

func (v *NullableGetProjectTemplateResponse) Set(val *GetProjectTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectTemplateResponse(val *GetProjectTemplateResponse) *NullableGetProjectTemplateResponse {
	return &NullableGetProjectTemplateResponse{value: val, isSet: true}
}

func (v NullableGetProjectTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


